package.json

Remove githook :) 
As a result of one of the comments. Since I already merged.

Remove githook

---

src/pages/Deposit.tsx
src/pages/SourceCode.tsx
src/pages/Trade.tsx

Renaming component names. No functionality changes.

Fix wrong component names in pages

---

src/components/DepositWidget/Row.tsx
src/components/DepositWidget/Table.tsx
src/components/DepositWidget/index.tsx
src/components/layout/Widget.tsx
src/pages/Deposit.tsx
yarn.lock

I did not have linter properly setup before.
This PR addresses the issues I introduced. Oops...

Fixed linter errors

---

src/api/exchange/DepositApiMock.ts
src/types.ts
test/api/ExchangeApi/DepositApiMock.test.ts
test/data/basic.ts
test/data/exchangeBalanceStates.ts

Refactor name of stateIndex and batchNumber to batchId

---

src/hooks/useEnableToken.ts

Fix memory leak on async operations

---

.babelrc
.eslintrc.js
package-lock.json
package.json
src/App.tsx
src/components/DepositWidget/Row.tsx
src/components/layout/Footer.tsx
src/components/layout/GlobalStyles.ts
src/components/layout/Header.tsx
src/components/layout/index.tsx
src/global.d.ts
src/pages/Deposit.tsx
src/utils/format.ts
src/utils/miscellaneous.ts
webpack.config.babel.js

Some suggestions
Only `.babelrc` changes are strictly necessary/useful

Misc suggestions

---

src/components/Wallet.tsx

Fix memory leak when connecting wallet and make the spinner spin :)

---

src/components/DepositWidget/Row.tsx
src/components/Wallet.tsx
src/hooks/useTokenBalances.ts
src/hooks/useWithdrawTokens.ts
src/types.ts
test/components/DepositWidget.components.test.tsx

**Includes**:
**The result:**
**Test**: Check web

Claimable instead of withdrawable

---

src/components/DepositWidget/Row.tsx
yarn.lock

Aparently when merging several PRs there was one change in one of the refactorized vars resulting in a bad automerge.
My bad. I think it's a good idea to rebase develop although git says that it can merge on it's own

Fix bad squashed merge

---

src/hooks/useHighlight.ts

Use Timeout rather than Interval

---

package-lock.json
yarn.lock

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars                                │
├───────────────┼────────────────────────────────────────────────── …
```

Fix npm audit warnings

---

src/components/Wallet.tsx

removed inline for styled components, small pr

swap inline styles for styled components

---

src/components/DepositWidget/index.tsx
src/components/TradeWidget/index.tsx
src/utils/miscellaneous.ts
test/utils/miscellaneous.spec.ts

Closes #162 
---
Small refactor to generalize a helper function and move it to utils.
Added unit tests.

Extracting utils function getTokens

---

src/components/DepositWidget/Row.tsx
src/hooks/useWindowSizes.ts

Somehow we managed to merge code that it's not formatted to develop branch.
This made that merging develop to another branch wouldn't allow to commit.
This PR solves the issue, but @W3stside please try to review why in your case, the `pre-commit` hook didn't stop it.

Fix formatting error

---

src/components/DepositWidget/index.tsx
src/utils/miscellaneous.ts
test/utils/miscellaneous.spec.ts

`getToken` util has an issue and is making the app to break in development.
The issue has to do with how the case insensitivity was implemented.
Also, added some test to prevent regression bugs for this.

Fix get token function

---

src/api/tokenList/tokenList.ts
src/types/global.d.ts
tsconfig.json

Json types

---

src/components/TradeWidget/index.tsx
src/hooks/usePlaceOrder.ts

Changes from #175 were accidentally overwritten by #191.
This PR add them back.

Fix bad merge on usePlaceOrder

---

src/hooks/usePlaceOrder.ts

Using safeState on usePlaceOrder

---

src/api/tokenList/Faucet_info.md

Fixed MD issues and updated Gemini faucet instructions

---

src/api/wallet/WalletApiImpl.ts
src/components/DepositWidget/Row.tsx
src/hooks/useTokenBalances.ts

Reducing logging

---

src/api/exchange/DepositApiImpl.ts
src/types/index.ts

Invert the orders of params for withdraw to match a change in the SC

fix withdraw method params order

---

src/components/LinkWithPastLocation.tsx

Properly handle all cases of `<Link to` prop
With correct types

rework LinkWithPastLocation

---

src/components/TradeWidget/TokenRow.tsx
src/hooks/usePlaceOrder.ts

Show pending+exchange balance in trade

---

src/components/LegalBanner.tsx
src/components/layout/index.tsx

minimal banner

---

src/components/LegalBanner.tsx

Just an alternative version with different colors :) 
It just makes the skull look prettier
Alt proposed:
Current one:

Change disclaimer colors

---

src/components/OrdersWidget/index.tsx
src/hooks/useOrders.ts

Part of #208 
---
New hook to get user orders
Build failed because I split changes into multiple PRs.
Following PR build works: #287

Adding useOrders hook

---

src/hooks/useWalletConnection.ts

Fix setState on unmounted in Wallet component when logging out

Fix setState on unmounted

---

src/components/layout/Header.tsx

Remove the `from` logic that it's causing navigation issues

Fix issue navigating to trade page

---

.travis.yml

This should make travis zip `./dist` folder and publish to releases when it sees a tag
Will see if it works when we make a new tag

Add auto release on tag

---

.travis.yml
package.json

Adds ipfs hashing on travis side
https://github.com/gnosis/dex-react/releases/tag/v0.2.1-9

Autorelease with ipfs hash

---

package.json
src/api/exchange/DepositApiImpl.ts
src/api/exchange/ExchangeApiImpl.ts
yarn.lock

Update contracts 0.1.3

---

src/components/Layout/Footer.tsx
src/components/Layout/index.tsx
src/pages/About.tsx
src/types/global.d.ts
webpack.config.babel.js

Show version in the footer, and add some info in the about part of the web.
Footer:
The versions are clickable, they'll take you to the project tag

Show version

---

src/App.tsx
src/api/wallet/WalletApiImpl.ts
src/api/wallet/WalletApiMock.ts
src/components/UserWallet/WalletComponent.tsx
src/components/UserWallet/index.tsx
src/hooks/useWalletConnection.ts
src/types/index.ts
src/utils/autoconnect.ts

New events allow for smaller delay between connection attempts

smaller wait for autoconnect with new events

---

src/App.tsx
src/html/index.html
webpack.config.babel.js

This isn't ideal and modifies base.href before scripts are injected
A better solution would be to adopt HashRouter, which also is not ideal

hack for hosting on ipfs

---

src/pages/ConnectWallet.tsx

closes #300 
Wallet Connect page reworded

wallet connect page wording

---

src/components/TradeWidget/OrderDetails.tsx
src/utils/autoconnect.ts

Fix initial web3 check

---

src/components/DepositWidget/Styled.tsx
src/components/Layout/Footer.tsx
src/components/Layout/Header/Navigation.styled.ts
src/components/Layout/index.tsx
src/components/LegalBanner.tsx
src/components/ThemeToggler.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/UserWallet/WalletComponent.tsx
src/styles/global.ts
src/styles/variables.ts

Proper colors for dark mode
Left to style:
- react-select component ([this can be useful](https://github.com/JedWatson/react-select/issues/3692#issuecomment-523425096))
- web3connect/WalletConnect modals
- probably more minor stuff

Dark colors / Footer behaviour

---

src/components/DepositWidget/Styled.tsx
src/components/Layout/Footer.tsx
src/components/Layout/Header/Navigation.styled.ts
src/components/Layout/index.tsx
src/components/LegalBanner.tsx
src/components/ThemeToggler.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/UserWallet/WalletComponent.tsx
src/styles/global.ts
src/styles/variables.ts
yarn.lock

Dark mode toggle with the dumbest dark mode style that still works
Please someone style radio buttons

🌘 dark mode 🌒

---

package.json
src/App.tsx
src/Console.tsx
src/api/wallet/WalletApi.ts
src/api/wallet/subscriptionHelpers.ts
src/declarations.d.ts
src/hooks/useTokenBalances.ts
src/utils/miscellaneous.ts
yarn.lock

To alleviate the pain of debugging on mobile in cases when can't debug as a remote device in Chrome devtools (not every in-app browser is recognized by Chrome).
A mobile-only console component

Mobile debug console

---

src/api/exchange/ExchangeApi.ts
src/api/exchange/ExchangeApiMock.ts
test/api/ExchangeApi/ExchangeApiMock.test.ts

Adding implementation for `placeValidFromOrders` to ExchangeApi
Requirement for #402

Adding implementation for placeValidFromOrders to ExchangeApi

---

src/App.tsx
src/components/Layout/index.tsx
src/components/OrdersWidget/index.tsx
src/components/PoolingWidget/index.tsx

Pooling: Enable Liquidity in Nav + transition Strategy to Liquidity (syntax)

---

src/components/PoolingWidget/index.tsx
src/utils/price.ts
test/utils/adjustAmountToLowerPrecision.spec.ts
test/utils/maxAmountsForSpread.spec.ts

From https://github.com/gnosis/dex-react/pull/427#discussion_r369159028

Making function on utils/price.ts accept obj parameters

---

src/components/PoolingWidget/AddFunding.styled.ts
src/components/PoolingWidget/AddFunding.tsx
src/components/PoolingWidget/CreateStrategy.tsx
src/components/PoolingWidget/DefineSpread.styled.ts
src/components/PoolingWidget/DefineSpread.tsx
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/PoolingWidget/SubComponents.tsx
src/components/PoolingWidget/index.tsx
src/hooks/usePlaceOrder.ts
src/styles/variables.ts

Last page, closes #403 
Consolidates step 4 into step 3, changes stepper to reflect this, better UX, word changing, darkmode compatibility

403/Step 4 Add Funding

---

package.json
src/api/deposit/DepositApi.ts
yarn.lock

Fix dex-js dependency usage
This is from the session with @alfetopito where we linked dex-react and dex-js and fixed the issues

Fix linking dex js

---

src/components/TradeWidget/TokenRow.tsx

Closes #416 
(Bug for setting `useMax` amount)

[Bug Fix] UseMax amount broken thing

---

src/components/DepositWidget/Form.styled.ts
src/components/Layout/Card/Card.tsx
src/components/PoolingWidget/DefineSpread.tsx
src/components/PoolingWidget/PoolingWidget.styled.ts
src/styles/global.ts

Fixes some padding/margin on smaller screens, fonts, hover issues as discovered while testing

Misc design fixes

---

src/api/deposit/DepositApi.ts
src/api/erc20/Erc20ApiMock.ts
src/api/exchange/ExchangeApi.ts
src/components/DepositWidget/useRowActions.tsx
src/components/OrdersWidget/useDeleteOrders.tsx
src/hooks/useEnableToken.ts
src/hooks/useTokenBalances.ts
src/hooks/useWithdrawTokens.ts
src/utils/miscellaneous.ts
src/utils/price.ts

`assert` utils fn has been moved to dex-js

---

.gitignore

For https://github.com/whitecolor/yalc
Great tool!

Ignoring yalc related files and folders

---

src/components/OrdersWidget/OrderRow.tsx

Do not display low balance warning for unlimited orders

---

src/hooks/useOrders.ts

small change to eleminate one rerender

useOrders optimization

---

src/hooks/useOrders.ts

Embarrassing mistake
Good job noticing, @alfetopito !

fix variable in useOrders

---

package.json
src/App.tsx
src/Console.tsx
src/components/EtherscanLink.tsx
webpack.config.babel.js
yarn.lock

Some improvements after I finally noticed that `parsed size > stats size` in bundle report :flushed: :see_no_evil:

Mini improv for bundle compilation

---

package.json
src/App.tsx
src/Console.tsx
src/PrivateRoute.tsx
src/api/wallet/WalletApi.ts
src/components/DepositWidget/useRowActions.tsx
src/components/EtherscanLink.tsx
src/components/Layout/Widget.tsx
src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/useDeleteOrders.tsx
src/components/PoolingWidget/index.tsx
src/components/UserWallet/WalletComponent.tsx
src/components/UserWallet/index.tsx
src/hooks/usePlaceOrder.ts
src/setupToastify.ts
src/toastify.ts
src/utils/autoconnect.ts
src/utils/onError.tsx
src/utils/transaction.tsx
webpack.config.babel.js
yarn.lock

- Lazy load all the things
- Add `<link rel="prefetch">` for all the things
- Make lots of sync code into async
- Dynamic wrapper for `react-toastify` that inits on first call
- Add a placeholder for `EtherscanLink` to avoid layout jitter
Some stuff may be broken as a result, though I tested
Audit json:
[localhost_5000-20200207T132733.zip](https://github.com/gnosis/dex-react/files/4170642/localhost_5000-20200207T132733.zip)
Possible further improvements:
- Host Token images locally and optimize them
- Images from github are not very web-friendly

Lazy loading + prefetching

---

src/components/TradeWidget/TokenRow.tsx

/trade page select on focus

---

src/const.ts
src/setupToastify.ts

Closes #477 
Depends on #502 for toast config
Doubling the time toast notifications are displayed.
From 5s to 10s.

477/ notifications displayed longer

---

src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/index.tsx

```js
const DEFAULT_FORM_STATE = {
sellToken: '0',
receiveToken: '0',
validUntil: '30',
}
```

482.5/fix form reset

---

src/components/Layout/Header/index.tsx
src/utils/time.ts

Addressing PR comment https://github.com/gnosis/dex-react/pull/541#discussion_r379441580

Rename formatSecondsToMinutes to formatSeconds

---

src/utils/autoconnect.ts

Addresses an issue with the autoconnect functionality after the lazy loading refactor

hotfix/0.8.2: Fix issue with autoconnect

---

src/components/TradeWidget/OrderDetails.tsx

Fix price and show also inverse price

---

src/components/PoolingWidget/index.tsx
src/components/TradeWidget/index.tsx
src/hooks/usePlaceOrder.ts

Closes #561 
Blocks on initial `onSubmit`
Unblocks on `txHash` via the `onSentTransaction` callback

block form only until txHash (dont wait mine)

---

webpack.config.babel.js

dex-react --> dFusion 
it might change later, but it makes user less confused

Change title name

---

package.json

fixes mock mode script post webpack bundle changes (webpack dashboard was removed)

fixed mock mode since webpack bundle changes

---

package.json
src/components/PoolingWidget/index.tsx
src/components/TradeWidget/OrderDetails.tsx
src/components/TradeWidget/index.tsx
src/hooks/usePlaceOrder.ts
webpack.config.babel.js

`git log v0.8.1..hotfix/0.8.2 --oneline --decorate=0`
0d03400 fixed mock mode since webpack bundle changes (#569)
d4dde50 Change title name (#567)
da5418a block form only until txHash (dont wait mine) (#563)
183e757 559/solve hardcoded 30min (#560)
af8d400 Fix price and show also inverse price (#558)
afad269 Fix issue with autoconnect

hotfix/0.8.2 (#558)

---

src/html/index.html

Not sure if this will work
Need to deploy to test

Arweave pathname detection

---

src/api/gasStation.ts
src/components/Tooltip.tsx
src/utils/autoconnect.ts
src/utils/miscellaneous.ts

Just remove some logs. Specially `console.log('styles', styles)` it was a bit noisy

Remove some debug logs

---

src/components/OrdersWidget/index.tsx

The PR was actually https://github.com/gnosis/dex-react/pull/571
From this comment https://github.com/gnosis/dex-react/pull/571#discussion_r381998751

Child element must be a React component

---

src/components/Layout/index.tsx
src/components/LegalBanner.tsx

Closes #535 
As title states - very simple implementation
I think in the future, with more persisted state, we should consider using [`localForage`](https://github.com/localForage/localForage) which allows for more than just strings
Using JSON parse/stringify is a pain

smart disclaimer - persist close

---

src/hooks/useOrders.ts

Fix orders loading first page

---

src/components/TokenSelector.tsx
src/components/UserWallet/UserWallet.styled.ts
src/styles/global.ts

Improved the styles for the tokenSelector:
I need assistance with adding some extra elements around the token selector, as per design:
- Show balance for each token
- Search input field
- Title + X close button

Improve tokenSelector styles.

---

src/components/TradeWidget/TokenRow.tsx

As per [comment](https://github.com/gnosis/dex-react/pull/551#discussion_r383975595)

Correct deps for readOnly useMemo

---

src/components/DepositWidget/index.tsx
src/components/LegalBanner.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/TokenSelector.tsx
src/components/Tooltip.tsx
src/components/TradeWidget/Price.tsx
src/components/UserWallet/UserWallet.styled.ts
src/styles/global.ts
src/styles/variables.ts

Styled the token selector (larger icon to match liquidity token selector)
Centered the no orders messaging:
Balance input slight padding improvement
WalletConnect modal styled
Connect a wallet modal styled. Mainly to support future client additions.
Styled the legal banner X icon
Styled the tooltips

Misc style updates.

---

src/components/TradeWidget/TokenRow.tsx

Fix error message in the balance always showing up

Fix balance always on error state

---

src/components/DepositWidget/Form.styled.ts
src/components/DepositWidget/Form.tsx
src/components/DepositWidget/Row.tsx
src/components/DepositWidget/Styled.tsx
src/components/DepositWidget/index.tsx
src/components/DepositWidget/useDepositModals.tsx
src/components/ErrorMsg.tsx
src/components/Layout/Header/Navigation.styled.ts
src/components/Layout/PageWrapper.tsx
src/components/Layout/Widget.tsx
src/components/Layout/index.tsx
src/components/LegalBanner.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/PoolingWidget/AddFunding.styled.ts
src/components/PoolingWidget/CreateStrategy.styled.ts
src/components/PoolingWidget/DefineSpread.styled.ts
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/PoolingWidget/index.tsx
src/components/TokenImg.tsx
src/components/TradeWidget/FormMessage.tsx
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/Price.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx
src/pages/About.tsx
src/pages/NotFound.tsx
src/pages/SourceCode.tsx
src/styles/global.ts

Fixing #630 
_(default state -> wrapping when large digits are present)_
_(pending)_
_(hover state)_
_(default state -> small digit)_
Fixing #628 
Fixing #623 
Fixing #589 (Created a `ContentPage` wrapper inheriting from PageWrapper for this, as a exported const)
**Also included**
- Applied a default font-size to the <main> element so we have a sensible fallback font size.
- Disabled autocomplete on the Tradewidget form.

Overall layout updates.

---

src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

Adds automatic focus on the sell amount input

Autofocus sell input

---

src/components/OrdersWidget/OrderRow.tsx

Fix price issue

---

src/components/TradeWidget/index.tsx

Close #634  
This is a proposal to solve the issue above describe. It's simple, do not disable the submit button.
use-form already handle the validation, also it's nice that it focuses in the input field that is incorrect.
i think this approach is more UX friendly

Do not disable the send button

---

src/components/OrdersWidget/index.tsx

change key to something sensical and not dumb

---

src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/index.tsx

* Shows filled/total ALSO for pending orders
* Shows expired ALSO for pending orders
* Include transaction hash into the status

Fix errors and show transaction

---

src/components/DepositWidget/index.tsx
src/components/DepositWidget/useRowActions.tsx
src/components/Layout/Header/Navigation.tsx
src/components/Layout/Header/index.tsx
src/components/Layout/index.tsx

Some optimizations I made when trying to address _flashing screen when opening Modali_ issue
Doesn't solve that problem but a nice to have nevertheless

Render optimization

---

src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/index.tsx

Fixing pending orders style.

---

src/components/ThemeToggler.tsx

temp disable dark mode - adds logic to clear localStorage

---

src/hooks/useTokenBalances.ts

Typo fix: bach -> batch

---

src/components/TradeWidget/OrderValidity.tsx

Visible button fix

---

package.json
src/api/exchange/ExchangeApi.ts
src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/OrdersWidget/index.tsx
src/components/PoolingWidget/index.tsx
src/components/ThemeToggler.tsx
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/index.tsx
src/hooks/useOrders.ts
src/hooks/usePendingOrders.ts
src/reducers-actions/pendingOrders.ts
src/utils/miscellaneous.ts
test/data/userOrders.ts

`master` >> `develop` merge
Possible issues:
~1. Not seeing pending orders showing up after sending tx~ **<-- Seeing it now, please confirm**
2. potentially wrong display of orders / lots of merge conflicts there that may been erroneously merged

0.9.0 master merged into develop

---

src/components/TokenSelector.tsx
src/components/TradeWidget/index.tsx

Addressing point: **Show balance for each token**
From https://github.com/gnosis/dex-react/pull/597
Finally did it, managed to align the balance

Display balance on trade page token selector

---

src/components/TradeWidget/index.tsx

Buy and sell order amounts were inverted for pending orders

---

package.json
src/components/DepositWidget/Form.tsx
src/components/TradeWidget/index.tsx

Merge hotfix v0.9.1

---

src/components/OrdersWidget/index.tsx

Closes #657 
Not that anything was broken. Just a nit pick refactor.
A next step would be to move filtered orders into global state. But, do we really need that?

Refactoring pending and regular orders classification on orders page

---

src/components/PoolingWidget/index.tsx
src/components/TradeWidget/InputWithTooltip.tsx

Couple small changes that were on my mind over the weekend

Misc changes

---

package.json
test/api/ExchangeApi/TokenListApiMock.test.ts
yarn.lock

Updating dex-js to add Chai

---

src/components/PoolingWidget/LiquidityButtons.tsx

Removes back button on last step (as per Anxos comment in #683)

PoolingWidget/index - remove back btn on last step

---

src/components/PoolingWidget/DefineSpread.styled.ts
src/components/PoolingWidget/DefineSpread.tsx
src/components/TradeWidget/FormMessage.tsx
src/components/TradeWidget/TokenRow.tsx
src/utils/validation.ts

Added formatted error under inputs - need to rework other inputs next in a separate PR

Pooling Input Error

---

src/components/PoolingWidget/LiquidityButtons.tsx
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/PoolingWidget/index.tsx

There were some remaining issues with back button addressed here:
1. disappearing back button when it shouldn't have been
2. formatting
3. not disabled when it should have been

Pooling interface back button rework

---

src/components/TradeWidget/index.tsx
src/styles/global.ts

Closes #676 
Rotates chevron on open/close state

Rotate OrdersPage chevron on click

---

src/components/PoolingWidget/index.tsx

Add links to devportal in liquidity page

---

src/api/wallet/WalletApi.ts
src/utils/flagCodes.ts
src/utils/mediaQueries.ts

Adds `screenSize` flag
Updates that flag when appropriate

OnChain analytics screen size

---

package.json
src/App.tsx
src/assets/md/FAQ.md
src/components/Layout/Footer.tsx
src/declarations.d.ts
src/pages/FAQ.tsx
webpack.config.babel.js
yarn.lock

Adds markdown loader (which has some problems with code blocks, but for now we don't have to care)
Adds tenative FAQ.md asset
access at /faq path
Feel free to suggest different styling
As for the text, would be better if headings were real headings not bold text, both in the doc and in md
Closes #699 after a fashion

FAQ and markdown

---

package.json
src/components/ConnectWalletBanner.tsx

Clicking on Wallet icon in Connect Widget opens web3connect modal
Closes #700

Connect in Connect Widget

---

src/components/TradeWidget/index.tsx

Fixing filled amount for pending orders

---

src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

I swear I commented on datatype in the PR where it was added, but can't find it anymore.
And it bothers me :worried:

Remove datatype

---

src/components/TokenSelector.tsx
src/components/TokenSelectorComponents.tsx

- No more empty selections on `Esc`
- Now filtering by token address as well

Yet another fix for token selector

---

src/components/ConnectWalletBanner.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts

Change ConnectWallet size

---

src/components/TradeWidget/index.tsx

Adds subtle outline when specific form inputs are focused

Focused styling

---

src/components/PoolingWidget/StepDescriptors.tsx

PRs #615 and #709 were reverted or just overwritten at some point
I suspect when StepDescriptor component was abstracted away in its own file

Restore commits

---

src/hooks/useOrders.ts

Amend something it should have never been merged to develop. 
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FWsGKzpdvWXY7jBNLqc%2Fgiphy.gif&token=ups" data-gitmeme-token="ups"><img src="https://media3.giphy.com/media/WsGKzpdvWXY7jBNLqc/giphy.gif" title="Created by gitme.me with /ups"/></a>

Amend todo

---

src/hooks/useTokenBalances.ts

When error happens during balance fetching, use last balance for that token
About refetching failed balance instead -- there'll be another balance fetch on newBlock in a few seconds anyway, so I don't think there's much need to spam requests.
Error can be simulated by blocking Metamask requests in devtools, only timing is difficult, need to block after `eth_blockNumber` request, during `eth_call` request for balance.
Closes #749

Use last balance on error

---

src/components/PoolingWidget/DefineSpread.tsx
src/components/Tooltip.tsx
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/TokenRow.tsx
src/hooks/usePopper.ts

Adds :question: tooltips, activated onClick
Styling is subject to change, of course

Help tooltips

---

src/components/TradeWidget/index.tsx
src/reducers-actions/index.ts
src/reducers-actions/trade.ts

Depends on #658 
Adding global state management to trade parameters.

Trade page global state

---

src/components/TradeWidget/index.tsx

Avoid displaying receive amount as NaN

---

src/hooks/usePriceEstimation.ts

Removing unused import

---

src/components/OrderBookWidget.tsx
src/pages/OrderBook.tsx

Some suggestions to make charts more react-like

Reactify charts

---

README.md

Just make it more official that we use Yarn. I was asked today by someone that tried to run the project...

Use yarn instead of npm

---

src/api/proxy/CacheMixin.ts
src/api/tokenList/TokenListApi.ts
src/components/TradeWidget/index.tsx
src/hooks/useAddTokenModal.tsx
src/services/factories/getTokenFromExchange.ts
src/services/index.ts
src/types/modali.d.ts

Allows to add token from url
try https://pr818--dexreact.review.gnosisdev.com/trade/0x45804880de22913dafe09f4980848ece6ecbaf78-USDC?sell=0&price=0&from=0&expires=2880

Add token form url

---

src/api/proxy/CacheMixin.ts
src/api/tokenList/TokenListApi.ts
src/components/DepositWidget/index.tsx
src/components/TradeWidget/index.tsx
src/const.ts
src/hooks/useAddTokenModal.tsx
src/hooks/useTokenBalances.ts
src/services/factories/getTokenFromExchange.ts
src/services/index.ts
src/types/modali.d.ts

Allows to add token in TokenSelector even when no Wallet connected
Assumes mainnet

Add token when disconnected

---

src/components/TradeWidget/TokenRow.tsx

- Changed text to reflect more clearly that users need to deposit. 
@anxolin Is this the correct file to do this? 
cc/ @c3rnst

Tooltip text change

---

package.json
src/components/OrderBookWidget.tsx
src/pages/OrderBook.tsx
yarn.lock

This PR pastes the code from https://czii9.csb.app/ into the Orderbook widget. The orderbook is based on https://www.amcharts.com/docs/v4/ and using the gnosis hosted price-estimation service to get data.
compare http://localhost:8080/book to https://czii9.csb.app/ and make sure they look a like,

[Orderbook] Rendering the transitive orderbook

---

src/reducers-actions/orders.ts

Closes #820
Last minute quick fix?

Reversing orders sorting. Latest on top

---

src/components/OrderBookBtn.tsx
src/components/OrderBookWidget.tsx
src/styles/global.ts

Desktop only for now. Mobile in progress.

Order book: Touch up design / modal size.

---

src/components/DepositWidget/Form.styled.ts
src/components/DepositWidget/Form.tsx
src/components/DepositWidget/Row.tsx
src/components/Layout/Card/Card.tsx

Add balances message.

---

src/components/Layout/Card/Card.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/index.tsx
src/styles/variables.ts

Fixes several CSS issues/missed things
1. Red colour on delete orders for dark mode
2. z-indexes for various comps
3. layout of orders widget on Trade page

Css fixes pre launch

---

src/components/TradeWidget/TokenRow.tsx

I think this PR can help #788 on top of what @biocom is working
What do you think?
It's just a plain link to the wallet, so user can deposit:

Add link to deposit to encourage to do the deposits

---

src/reducers-actions/orders.ts

Follow up to https://github.com/gnosis/dex-react/pull/853#discussion_r406006081

Not reversing orders array in place because that's bad

---

src/components/OrderBookBtn.tsx

Just a test addressing comment: https://gnosisinc.slack.com/archives/CSGLUC1BN/p1586443057005800
"I like the pop up but it took me some time to find the button"

Add icon to make the order book more visible

---

package.json
yarn.lock

Just that, update dex-js to v0.2 😊

Update dex-js to v0.2

---

src/api/tokenList/TokenListApi.ts
src/api/tokenList/TokenListApiMock.ts
src/components/TokenOptionItem.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/index.tsx
src/hooks/useBetterAddTokenModal.tsx
src/hooks/useTokenBalances.ts
src/services/index.ts

~Nigh unstyled, but works alright~
Anyone is welcome to style it further
try https://pr866--dexreact.review.gnosisdev.com/trade/0x45804880De22913dAFE09f4980848ECE6EcbAf78-0x1d9a3cef66b01d44003b9db0e00ec3fd44746988?sell=0&price=1.01768&from=&expires=2880

Better token add modal from URL

---

src/pages/About.tsx

Just update 1 link to dune, I'll go with just one review on this one :)

Update dune dashboard

---

src/components/OrderBookBtn.tsx
src/components/PoolingWidget/DefineSpread.styled.ts
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/PoolingWidget/TokenSelector.styled.ts
src/components/PoolingWidget/index.tsx
src/components/TradeWidget/TokenRow.tsx
src/styles/variables.ts

For ticket #867
- Added message with a link to the Balances (wallet) page.
- Made the inputfield have a white background. In my opinion the grey inputfield inside the grey container wasn't clear.

Add liquidity message.

---

src/components/TradeWidget/index.tsx

closes #874 
Had to fix bug with resetting `validFrom` `validUntil` when setting `ASAP` or `Never`, respectively

fixes saved trade params & second tx error

---

src/components/OrderBookBtn.tsx
src/components/TradeWidget/OrderValidity.tsx

Fix button clicks

---

src/styles/global.ts
src/styles/variables.ts

Fixes invisible Close `X` button in Modali
Also fixes Order Settings button visibility transition (which happened previously, was fixed at some point and now broke again), by explicitly specifying which props to transition

Misc style fixes

---

src/components/OrderBookWidget.tsx

Support dark mode in the orderbook.

---

src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

To fix https://github.com/gnosis/dex-react/issues/873

Fix button layout desktop/mobile.

---

src/hooks/useBetterAddTokenModal.tsx

Small fix for rinkeby only problem of infinite fetching on wrong network
Compare 
http://dex.dev.gnosisdev.com/trade/0x45804880De22913dAFE09f4980848ECE6EcbAf78-USDC?sell=0&price=0&from=&expires=2880
and
https://pr898--dexreact.review.gnosisdev.com//trade/0x45804880De22913dAFE09f4980848ECE6EcbAf78-USDC?sell=0&price=0&from=&expires=2880
on rinkeby

Fix rinkeby Token fetch

---

package.json
yarn.lock

Updating dex-js

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts

Using new prod endpoint for dex-price-estimator

---

src/html/index.html

Fixed by modifying the meta viewport setting in the main html file.

Fix meta viewport

---

src/styles/global.ts
src/styles/variables.ts

```css
button:disabled:hover {background-color: initial;}
```
ended up white on white
Closes #900

Fix button hover color

---

src/api/index.ts
src/pages/About.tsx

Update thegraph links

---

src/components/PoolingWidget/AddFunding.tsx

Renamed `Wallet page` to `Balances page`

---

package.json
yarn.lock

https://github.com/gnosis/dex-js/pull/136
https://github.com/gnosis/dex-js/releases/tag/v0.2.2
https://www.npmjs.com/package/@gnosis.pm/dex-js/v/0.2.2

Bumping dex-js to update WBTC decimals

---

src/const.ts

* Adds sUSD
* Adds an env var to easily mantain this list

Add sUSD to liquidity and allow to modify the list using env vars

---

package.json
src/api/index.ts
src/components/PoolingWidget/AddFunding.tsx
src/const.ts
src/pages/About.tsx
src/utils/miscellaneous.ts
test/data/userOrders.ts
yarn.lock

```python
Update thegraph links (#919)
@anxolin
anxolin committed 1 hour ago
Renamed `Wallet page` to `Balances page` (#925)
@alfetopito
Leandro Boscariol
alfetopito and Leandro Boscariol committed 2 minutes ago
907/filled orders to closed tab (#920)
@alfetopito
Leandro Boscariol
alfetopito and Leandro Boscariol committed 1 minute ago
Bumping dex-js to update WBTC decimals (#921)
@alfetopito
Leandro Boscariol
alfetopito and Leandro Boscariol committed 1 minute ago
```

🔥 HOTFIX/v0.11.1 🔥

---

src/components/TradeWidget/index.tsx

Fixes #881 by disabling it outright

Only resubmit on mainnet

---

src/components/PoolingWidget/AddFunding.tsx

Adjusting the wording as requested

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts
src/components/OrderBookWidget.tsx

Address this comment https://github.com/gnosis/dex-react/pull/937#discussion_r410290902
* Defines a new method in the API that returns an URL for querying the order book
* Uses that in the widget
* Small refactor for getting the base URL

Use production URL for order book

---

src/components/Layout/index.tsx
src/components/LegalBanner.tsx

Closes #887 (skull)
LegalBanner: change skull font to icon
1. moves out props for children prop
2. uses fontawesomeicon skull

Fix 💀  [Super Important] 💀 💀 💀 💀 💀 💀 

---

src/components/DepositWidget/Form.tsx
src/components/TokenOptionItem.tsx
src/hooks/useBetterAddTokenModal.tsx
src/hooks/useTimeRemainingInBatch.ts

- Fixes devportal link
- Fixes /faq link
Closes #942

Misc fixes

---

src/components/TokenSelector.tsx
src/components/TradeWidget/index.tsx
src/pages/OrderBook.tsx

Fixes #778 
Fixes overflow scrollbar on Chrome (not every Chrome even)
Fixes focus change on Enter when inputting gibberish
Fixes typo in styling in OrderBook

Misc fixes (TokenSelector + styling)

---

src/components/TradeWidget/index.tsx
src/services/factories/tokenList.ts

Clearing this todo entry:
TODO: try again only for the ones that failed

More robust token id fetching

---

src/api/tokenList/TokenListApi.ts
src/services/factories/tokenList.ts

My attempt at https://github.com/gnosis/dex-react/pull/1004

Fix tcr override - second opinion

---

README.md
config-default.yaml
test/config.spec.ts

Depends on #987 
~Pending legal review regarding mention to DxDao's TCR and wording.~ Done
Superseding https://github.com/gnosis/dex-react/pull/997

Updated README with details for Config options

---

README.md
package.json
src/api/erc20/Erc20Api.ts
yarn.lock

Address some minor issues from the release

Release misc

---

package.json
yarn.lock

Fix the sudden broken travis. Updates @babel/preset and core

Try to fix broken travis

---

src/components/DepositWidget/Row.tsx
src/components/DepositWidget/useRowActions.tsx
src/components/OrderBookWidget.tsx
src/components/OrdersWidget/OrderRow.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/TokenRow.tsx
src/hooks/useEthBalance.ts
src/hooks/useTokenBalances.ts
src/utils/format.ts

Closes #1009 
Merges into #1051 
Adds format smart to dex-react
OrderBookWidget still not perfect but will work well enough for this iteration
Will likely require changes to dex-js in future to allow for more custom decimal assignment for different number thresholds

Add format smart

---

src/components/TradeWidget/Price.tsx

Closes issue with Price input having too large symbols

Price Input: deal with large symbols

---

package.json
src/components/WrapEtherBtn.tsx

Handle dimas edge case (#1037)

Release/1.0: Release candidate 1

---

src/components/TradeWidget/Price.tsx

Closes #1065 
Fixes inputs css issues in PriceValidity

dont target radio container div

---

src/components/OrderBookBtn.tsx
src/components/OrderBookWidget.tsx
src/components/TokenImg.tsx
src/components/TradeWidget/Price.tsx

* Fixing token images on dark mode (#1061) 
* Improve order book representation (#1062)
* dont target radio container div (#1068)

Release/1.0: Release candidate 2

---

src/api/exchange/ExchangeApi.ts
src/api/exchange/ExchangeApiMock.ts
src/api/exchange/utils/decodeAuctionElements.ts
src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/index.tsx
src/components/PoolingWidget/index.tsx
src/components/TradeWidget/index.tsx
test/api/ExchangeApi/ExchangeApiMock.test.ts
test/api/ExchangeApi/decodeOrders.test.ts

Refactoring order status to make it easier to split it out into tabs.
Same vibe as https://github.com/gnosis/dex-react/pull/1103

Order status refactoring

---

src/components/TradeWidget/index.tsx

widen orderswidget in trade page

---

src/components/TradeWidget/Price.tsx

Fix error removing trailing zeros for price

---

src/components/TradeWidget/index.tsx
src/hooks/useQuery.ts
src/reducers-actions/trade.ts

The default params fo the trade sets "Never" as the default expiration date

Trade Page: Do not expire by default

---

README.md
config-default.yaml
package.json
src/api/wallet/WalletApi.ts
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/index.tsx
src/const.ts
src/hooks/useQuery.ts
src/hooks/useTokenBalances.ts
src/reducers-actions/trade.ts
src/types/config.ts
src/utils/autoconnect.ts
src/utils/miscellaneous.ts

Merge fixes from 1.0.2 and 1.0.3 to develop
IMPORTANT: Do not SQUASH and MERGE. Only MERGE!

Merge v1.0.3

---

package.json
yarn.lock

Fixes #1129 
Depends on gnosis/dex-js#155

Fix price format in orders

---

src/components/Layout/Header/index.tsx

Added batch id to header

---

src/components/DepositWidget/Form.styled.ts
src/components/InputBox.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

Closes #611 
To test: pick a non enabled token (check Balances page) and enable
Not enabled:
Enabling:

add enableToken to TokenRow (TradeWidget)

---

config-default.yaml
src/components/DepositWidget/Row.tsx
src/components/TokenOptionItem.tsx
src/components/TokenSymbol.tsx
src/hooks/useManageTokens.tsx
src/types/config.ts

Add link :warning:

---

config-default.yaml

Shame! :bell:  Shame! :bell: 
Closes #1190

Fix token name

---

src/components/TradesWidget/index.tsx

CSV columns rename from CamelCase

CamelCase -> human readable

---

src/components/Layout/Header/index.tsx

Adds tooltip to `Current batch: <N> ?` with link to devdocs
Can use a shorter description, suggestions?

Batch explanation tooltip

---

src/components/TradeWidget/PriceEstimations.tsx

Inverting price estimation market

---

src/components/OrdersWidget/OrderRow.tsx
src/components/TradeWidget/OrderValidity.tsx
src/hooks/usePlaceOrder.ts

ASAP > Now and related tags

---

src/components/TradeWidget/index.tsx

1 .Disconnected
2. Submit order
3. Connect prompt
4. Go on with order

Reenable connect+tx behavior

---

src/components/DepositWidget/index.tsx

Fixes tokens disabled in Manage Tokens still showing in DepositWidget

Fix disabled tokens list

---

src/components/TradeWidget/index.tsx

Resetting prices when token selection changes

---

src/components/OrdersWidget/index.tsx

Renaming Fills tab to Trades

---

src/components/TradeWidget/PriceEstimations.tsx

Making price suggestion buttons round

---

src/components/ThemeToggler.tsx
src/const.ts

I bumped into this while doing another PR, so aligned with not mixing unrelated things. Here is a simple one :)
Gets rid of our old name "Fuse"

Remove fuse

---

src/components/DepositWidget/Row.tsx

add fullAmount to tooltip balances

---

src/components/TradeWidget/TxMessage.tsx

Styles tx confirmation modal's low volume warning

Style low volume warning - TX Confirmation modal

---

src/api/deposit/DepositApi.ts
src/api/deposit/DepositApiMock.ts
src/components/DepositWidget/Row.tsx
src/components/DepositWidget/Styled.tsx
src/components/DepositWidget/index.tsx
src/components/DepositWidget/useRowActions.tsx
src/components/Layout/Card/Card.tsx
src/hooks/useTokenBalances.ts
src/reducers-actions/tokenRow.ts
src/types/index.ts
test/api/ExchangeApi/DepositApiMock.test.ts
test/components/DepositWidget.components.test.tsx
test/data/exchangeBalanceStates.ts

Closes #1136 
add getLastCreditBatchId to depositApi & useTokenBalances claimable check
Not sure how best to check, any ideas?

add getLastCreditBatchId to depositApi & useTokenBalances claimable check

---

.travis.yml
src/api/wallet/walletUtils.ts

Testing out a small fix involving a comment mid `if` block

Maybe fixing travis builds? removed comment

---

src/components/TradeWidget/TxMessage.tsx
src/utils/minFee.ts
test/utils/minFee.spec.ts

Closes #1322 
Message is up for discussion, as well as further styling, of course.

Recommend min sell amount

---

.travis.yml
package.json

`release_notes_file` [gets filled correctly](https://travis-ci.com/github/gnosis/dex-react/builds/180490398#L948-L950), but doesn't get posted to github
Same as with body

Release notes file for travis

---

src/components/TradeWidget/TxMessage.tsx
src/utils/minFee.ts
test/utils/minFee.spec.ts

Subsidize factor change

---

src/components/TradeWidget/index.tsx

Fixes price validation on price reset

Fix price validation on token change

---

src/pages/OrderBook.tsx

Just some small improvments
- improve layout, make it bigger, smaller input
- make batch id numeric, so we can increment easily and it does some free validation

Make orderbook bigger

---

src/components/TradeWidget/Price.tsx
src/components/TradeWidget/PriceEstimations.tsx
src/components/TradeWidget/index.tsx

Fixes representation of data on price suggestion:

Fix Price Suggestion price wording

---

src/components/Layout/Header/Header.styled.ts
src/components/Layout/Header/index.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/UserWallet/WalletComponent.tsx

Light mobile:
Light web:
Dark mobile:

easier logout process

---

src/components/Layout/Header/Header.styled.ts
src/components/Layout/Header/index.tsx
src/components/UserWallet/UserWallet.styled.ts

Fixes overflow issue for iOS browser
Moves `header/index.ts` styled components to `header/Header.styled.ts` where they BELONG

UserWallet CSS for iOS fix

---

travis/deploy_pull_request.sh

Add the storybook link in travis too
**Review not needed for now: Waiting for travis**

Add Storybook link using PRaul

---

.travis.yml

<sub><sup><sub>Also build storybook on master and develop</sub></sup></sub>
<sup><sub>Also build storybook on master and develop</sub></sup>
<sub>Also build storybook on master and develop</sub>

Also build storybook on master and develop

---

src/App.tsx
src/components/layout/TradingLayout/index.tsx
src/components/layout/index.ts
src/pages/NotFound2.tsx
src/pages/Trading.stories.tsx
src/pages/Trading.tsx

* Adds a new layout for the v2.0 so we can start shaping it
* Add a new route for `/v2` that displays a trading page
* Maintains all the old routes (so we can maintain v2 and v1 in the same branch)
* Creates the story books for the new trading page
* Creates the story books for the new and old layout
**NOTE 1**: Not found page was duplicated, I know I can refactor, but probably we want to let them be different. We can see what we do after we have some designs.
**NOTE 2**: It doesn't use the GlobalStyles on purpose. I think v2 can define styles in the components and avoid using this global styles.
**TEST**:
* https://pr1404--dexreact.review.gnosisdev.com/v2
* https://pr1404--dexreact.review.gnosisdev.com/v2/one-weird-page

Trade layout

---

src/utils/minFee.ts

Rounds to the next 100$ instead of the next 250$

Round to next 100$

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts
src/components/TradeWidget/TxMessage.tsx
src/components/TradeWidget/index.tsx
src/components/TradeWidget/utils.ts
src/components/trade/Price.stories.tsx
src/components/trade/Price.tsx
src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx
src/hooks/usePriceEstimation.ts

Fixes #1421 
The inverse logics are a bit chaotic 😅
I tried to get to the root cause of why the token were wrong, and at the end there was many part together having the inverted logic, some errors were making other errors right! What a nightmare of debugging! This parts need to be refactored asap.
I tried to do every change as an individual commit, so maybe is interesting to review the commits in order. Each one, tries to make the code more readable regarding prices, or fixes a price logic error at one point of the app. 
Note that when something was fixed, it was showing another error in other part of the app. So the process was continue correcting every component until it was making sense again.
Please, review this PR in detail in case there's new issues.

Fix wrong quote

---

src/components/TradeWidget/TxMessage.tsx

Update link to match this PR: https://github.com/gnosis/dex-docs/pull/45

Update link to dev portal

---

src/App.tsx

Issue with initial selection

---

src/api/earmark.ts
src/api/exchange/ExchangeApi.ts
src/api/wallet/WalletApi.ts
src/api/wallet/composeProvider.ts

> Multiply 5K by the number of IDs being deleted, and add it to the normal estimation
Closes ##1444

Extra gas per order for order cancellation

---

src/components/trade/LastTrades/LastTrades.stories.tsx
src/components/trade/LastTrades/LastTradesWidget.stories.tsx

The test data was moved. This fixes the issue of the merge of the PR of the Last Trades
The bad merge breaks `develop`'s storybook

Fix some moved dependency

---

src/components/OrdersWidget/index.tsx

Don't count reverted trades we don't display

---

src/services/factories/tokenList.ts

As we commented in PR https://github.com/gnosis/dex-react/pull/1489, the logic for getting the list of tokens is too complex.
Dima, made a proposal in this comment:
https://github.com/gnosis/dex-react/pull/1489#discussion_r500157569
This PR is a reiteration in his proposal
* Simplifies logic, less loops
* Break the logic in more scoped and defined functions
* Removes some weird API signature, where we were returning a String instead of TokenDetails when there was not a valid ERC20

Improve fetch tokens

---

src/components/TradeWidget/index.tsx
src/components/TradeWidget/utils.ts
src/utils/miscellaneous.ts

WIP, TradingWidget has a token selection / network change mess. 
I try to do several workarounds, this is an attempt that apparently works if the user didn't trade DAI before.

Make a default selection per network

---

src/api/wallet/WalletApi.ts
src/components/Settings/WalletConnect.tsx
src/utils/walletconnectOptions.ts

Can test with MetaMask mobile, for example

WalletConnect for xDAI

---

src/api/tokenList/TokenListApi.ts
src/api/tokenList/TokenListApiMock.ts
src/hooks/useOrders.ts
src/hooks/useTokenList.ts
src/services/factories/tokenList.ts

Addresses several issues:
1. data load speed on xDAI (ordersWidget)
2. isListReady, necessary for not showing stale data, mixed with useEffect logic was blocking updates
3. types

Investigate orders load speed

---

src/components/TradesWidget/TradeRow.tsx
src/components/common/SwapPrice.tsx

Recreated this PR: https://github.com/gnosis/dex-react/pull/1494, that was merged too early (had a waterfall dependency, so I reverted the merge and recreated this PR)
The PR is already reviewed and approved ✅

Show buy sell fills

---

config-default.yaml
test/config.spec.ts

Adds production xDAI price estimation URL

xDAI price estimate prod URL

---

src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/TradesWidget/TradeRow.tsx
src/components/TradesWidget/index.tsx
src/components/layout/PageWrappers.tsx
src/components/layout/SwapLayout/index.tsx
src/const.ts
src/styles/variables.ts

Merges into #1535
Addresses [this comment from @anxolin](https://github.com/gnosis/dex-react/pull/1535#issuecomment-709940162)
Involves some design changes that may break in places I haven't seen yet. Implements horizontal scrolling of table when necessary

Trades split limit fill price

---

README.md

Closes #1505 
Simple README link to Wiki on compatible networks and instructions

xDAI README update with Compatible Networks section

---

src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx
src/hooks/useBestAsk.tsx

Part of #1476 
Adds `useBestAsk.ts` hook to `PriceSuggestionsWidget.tsx`

[Smart Quote]: Add useBestAsk hook to PriceSuggestionsWidget

---

src/components/trade/PriceImpact/PriceImpact.styled.ts
src/components/trade/PriceImpact/index.tsx
src/components/trade/PriceImpact/utils.ts
src/styles/variables.ts

Merges into #1544 
Addresses comments inside #1544 
Notable the discussion found in the waterfall PR [here about the different warnings](https://github.com/gnosis/dex-react/pull/1544#issuecomment-714393317)
Warnings and colours and labels, oh my!

Price impact warnings pr comments

---

.travis.yml

Fixes broken travis builds due to node version

Fix .travis.yml NODE version > sticky to 12

---

src/data/quoteTokenPriorities.ts

xDAI-smart-quote-priority-list

xDAI Token Priority list

---

src/components/TradeWidget/TxMessage.tsx
src/components/TradeWidget/index.tsx
src/components/trade/PriceImpact/utils.ts
src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx
src/hooks/usePriceEstimation.ts

Fixes broken warnings when adjusted smart quote markets come into play
Makes sure to use correct price and absolute token pair in price impact calculation

[Price Impact] Fix broken warnings on adjusted market

---

src/components/TradeWidget/TxMessage.tsx
src/components/TradeWidget/index.tsx
src/components/common/FormMessage.tsx
src/components/trade/PriceImpact/index.tsx
src/components/trade/PriceImpact/types.ts
src/components/trade/PriceImpact/usePriceImpact.ts
src/components/trade/PriceImpact/utils.ts
src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx
src/hooks/useBestAsk.tsx
src/hooks/usePriceEstimation.ts

Part of #1456 
Merges into #1544 
Adds warnings into TX Confirmation modal

[Price Impact] Confirmation Modal Warnings

---

src/components/TradeWidget/index.tsx
src/components/TradeWidget/utils.ts
src/components/trade/PriceSuggestions/PriceSuggestionItem.tsx

Fixes price calculation and fixes warnings from small calc errors

[Price Impact] - Fix price calculation and price warnings

---

.gitignore
.travis.yml
package.json

Adds eslint cache
Try to run:
```bash
yarn lint:js
yarn lint:js
vim src/components/DepositWidget/useRowActions.tsx
yarn lint:js
```

Add eslint cache

---

.eslintrc.js
cypress/plugins/index.js
package.json
yarn.lock

Add cypress eslint
https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-an-ESLint-plugin-for-Cypress-or-a-list-of-globals

Add eslint for cypress

---

src/components/layout/TradingLayout/GlobalStyles.ts
src/components/layout/TradingLayout/Header.tsx
src/components/layout/TradingLayout/index.tsx
src/components/layout/TradingLayout/variablesCss.ts
src/pages/Trading.tsx
src/styles/globalTrading.ts

Break down #1591 
This is the first of a series of PRs aiming to break down #1591 
The PR adds a Global Style (basically adding some defaults), adds some variables for the colors, and leaves some placeholders for future components that will come in different PRs.

V2 add global styles

---

src/components/TokenPairSelector/TokenPairSelector.stories.tsx
src/storybook/decorators.tsx

* Creates a global style decorator for the generic layout of v2
* Uses it in the stories of the TokenPairSelector

Create global style decorator

---

src/components/layout/GenericLayout/TradingLayout.stories.tsx
src/components/layout/LegacyTradeLayout/LegacyTradeLayout.stories.tsx
src/storybook/RouterDecorator.tsx
src/storybook/decorators.tsx

Just moves the router decorator to the file were we have all the other decorators
for now is small enough so we can keep them in the same file

Move router decorator with his friends

---

src/app/TradeApp/index.tsx
src/app/TradeApp/pages/Trading.tsx
src/components/OrderForm/index.tsx
src/components/TokenPairSelector/index.tsx
src/components/TokenPairSelectorList/index.tsx
src/components/layout/GenericLayout/GlobalStyles.ts
src/components/layout/GenericLayout/Menu/index.tsx
src/components/layout/GenericLayout/variablesCss.ts

- Starting to work on adding a OrderFrom component.
- Cleanup global styles and variables

Add order form /w components

---

cypress/support/index.d.ts
src/components/OrderBuySell/index.tsx
src/components/common/Tabs/TabContent.tsx
src/components/common/Tabs/TabItem.tsx
src/components/common/Tabs/Tabs.tsx

@biocom It's not major changes but changes that should have been included. 
Nice work on this stuff btw, just make sure to get 2 approvals eh? :)

V2 Tabs comments

---

src/components/TradeWidget/index.tsx
src/components/TradeWidget/utils.ts

`TokenAdder` weren't rendered because its parent component `TradeWidget` was no longer rendered. Moved it up the tree to always render
Try [this link](https://pr1641--dexreact.review.gnosisdev.com/trade/0xE59064a8185Ed1Fca1D17999621eFedfab4425c9-USDC?sell=923.373903383166004671&price=0.5000079797667986942) to add PrimeDAO token

Fix TokenAdder

---

src/api/wallet/composeProvider.ts
src/const.ts

Sample implementation of rate limiting provider calls

Rate limit calls

---

src/components/Toggle.tsx
src/components/common/Button/index.tsx
src/hooks/useThemeManager.tsx
src/reducers-actions/index.ts
src/reducers-actions/theme.ts
src/reducers-actions/tokenRow.ts
src/storybook/decorators.tsx
src/theme/index.ts
src/theme/index.tsx
src/theme/styles/colours.ts
src/theme/styles/global.ts
src/theme/styles/index.ts
src/theme/types.ts
src/theme/utils.ts

Part of #1660 and :droplet: 's into #1664 
This PR adds our theme colour palette inside `theme > styles > colours` and the start of its types inside `theme > types` - relevant code all exported inside `theme > index.ts`
Colour palette is very minimal right now, can be iterated over as need be. Right now the `Color` type resembles:
```ts
interface Colors {
// text
primaryText1: Color
secondaryText1: Color
secondaryText2: Color
textDisabled: Color
// backgrounds / greys
bg1: Color
bg2: Color
bgDisabled: Color
// gradients
gradient1: Color
gradient2: Color
// Base
white: Color
black: Color
red1: Color
red2: Color
red3?: Color
green1: Color
green2: Color
green3?: Color
yellow1: Color
yellow2: Color
yellow3?: Color
blue1: Color
blue2: Color
blue3?: Color
}
```
and the colour palettes …

[V2 #1660 Style Rework] Add Theme colour palette, types, and fix subsequent errors
