gnosis/gp-v1-ui

src/utils/format.ts

Part of #66 
Addresses internationalization of amounts.
Note that since we didn't use the standard formatter, the comman/decimal symbols where hardcoded.
This PRs get's those symbols for the user, and uses them for the formatting
**Test**
- Run 
- Change locales
- check that the decimal/thousands symbol it's ok

Internationalize amounts

---

src/components/DepositWidget/Form.tsx
src/components/DepositWidget/Row.tsx
src/components/layout/GlobalStyles.ts
src/utils/ethereum.ts
src/utils/format.ts
test/data/erc20Allowances.ts
test/data/erc20Balances.ts
test/data/exchangeBalanceStates.ts
test/utils/formatAmount.spec.ts
test/utils/parseAmount.spec.ts

**Includes**
**Utils**
Aditionally improved and added some aditional utils:
**Bonus :)**
**Do not include**
It doesn't include the call to the service, update of the balances, or rollback in case of error.
**Test**:
* `yarn test`
* Check link: https://pr76--dexreact.review.gnosisdev.com

Deposit form

---

src/App.tsx
src/api/wallet/WalletApiMock.ts
src/components/DepositWidget/index.tsx
src/components/Wallet.tsx
src/components/layout/Header.tsx
src/hooks/useEnableToken.ts
src/hooks/useTokenBalances.ts
src/hooks/useWalletConnection.ts
src/pages/ConnectWallet.tsx
src/types.ts

This PR allows to connect and disconnect a wallet, provides a simple hook with the wallet information, and allows to protect pages that require a connected wallet.
Apologies cause the PR is a big bigger than expected. All the changes are related, I hope that with the explanations it's a bit clear all the changes involved.
Includes:
**Out of the scope of the PR**
- It doesn't style a lot the wallet information (#89 )
- It doesn't implement the Web3 implementation. Only connects using the mock. (#81 )
- It doesn't remove the `TODOS` in the paces where there was a `// TODO: Review after implementing connect wallet.` because this will be handled in a separate PR (#105)
- I think it's convenient to do a autoconnect for the mock implementation, so we don't need to connect for quick testing and …

Connect/Disconnect wallet and provide Wallet info

---

src/const.ts
src/hooks/useEnableToken.ts
src/hooks/useTokenBalances.ts
test/data/erc20Allowances.ts
test/data/erc20Balances.ts
test/utils/formatAmount.spec.ts
test/utils/formatAmountFull.spec.ts
test/utils/parseAmount.spec.ts

Address one of the problems mentioned in #106 
- When enabling the tokens we set the maximun amount. That's a huge number `2**256-1`
- When checking if the token is enabled, we relax the conditin, but still an arbitrarily huge number that is much smaller than the max: It uses `2**128`

Change check for enabled tokens

---

src/components/DepositWidget/Form.tsx

This PR fixes the infinity loop that the validation is generating.
It solves the issue that can be seen in the console when doing a deposit or withdraw:

Fix infinity loop

---

src/components/TradeWidget/TokenRow.tsx

Closes #170 
Adding `use max` button and removing hidden button from green exchange amount:

Added use max button on sell token

---

src/components/TradeWidget/OrderDetails.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx
src/const.ts
src/utils/format.ts

Part of #102 
Depends on #165 
---
Adding the order details with a simple price calculation, as per the requirement **RF.2.5 Swap widget: Create sell order**.

Displaying order details when both inputs are filled

---

src/components/DepositWidget/useRowActions.tsx

Fixes `enableToken` bug
But on a bigger note, we _really_ should change the API functions to accept `Object args` - see issue #193 to avoid issues as these.

switched improper arg placement in enableToken

---

src/components/TokenSelector.tsx

Closes #147  
Depends on #175, #191 
---
Small refactor to remove inline styles.
Added margin to the left of the option text.

Refactoring inline styles on TokenSelector

---

src/components/TradeWidget/TokenRow.tsx
src/utils/format.ts
test/utils/adjustPrecision.spec.ts
test/utils/parseAmount.spec.ts

Depends on #175 
---
Proposal to use BN instead of Number on Trading widget.
To be able to work with the proper precision for each token, this change enforces only max precision chars are used for each respective token, preventing the user from inserting more than given precision.
Try it out and let me know what you think
---
**Edit**: Based on comments, did a small refactor on the validation:

Use BN over Number

---

src/components/TradeWidget/index.tsx

This bug is again because TradeWidget saves tokens state locally and believes it to be the source of truth (not chain state), which comes from the fact we don't differentiate enough between local state (token list in this case)  and network-dependent token balances from the blockchain.
This is a quick fix for now.

fix wrong address on sell|buy token

---

src/api/wallet/WalletApiImpl.ts
yarn.lock

Fixing these linters errors/warnings:
```
/home/alfeto/work/dex-react/src/api/wallet/WalletApiImpl.ts
139:41  error    Unexpected empty arrow function           @typescript-eslint/no-empty-function
164:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
174:48  error    Unexpected empty arrow function           @typescript-eslint/no-empty-function
```

Fixing linter errors after latest update from dependabot

---

src/components/TradeWidget/index.tsx
src/hooks/useURLParams.ts

Bug became noticeable with addition of `/orders` route
Reproduce:
1. Go to https://pr287--dexreact.review.gnosisdev.com/
2. Connect Wallet
3. Go to `/orders`
4. Click `Trade` Link
5. Click back (browser navigation back) once
6. Be amazed
7. Click back once more

Fix double history on /trade route

---

src/api/tokenList/tokenList.json

The rinkeby address of DAI was already MCD.
But the mainnet address was not.
This PR corrects this.

Update TokenList to use MCD DAI for mainnet

---

src/components/Layout/Footer.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/UserWallet/index.tsx

- Makes QR responsive in size (canvas can't scale outside of init size)
- Footer was fat on pages with height < 100vh
Before:
After:
Feel free to resize QR width % as you see fit

styling suggestions

---

src/api/index.ts
webpack.config.babel.js

Removed the instantiation of the deposit API, it's not required since it's the same contract as the deposit API.
It removes stuff, and the app apparently still works :P 
Aditionally, it renames some vars in ErcApi to be more consistent

Remove deposit API instance

---

src/components/DepositWidget/index.tsx
src/components/DepositWidget/useRowActions.tsx
src/hooks/useTokenBalances.ts

Follow up from https://github.com/gnosis/dex-react/pull/338#pullrequestreview-335556679
Removing 'manual' interface updates.
Balances states now becomes read only, with the updates coming directly from the network.
Keep in mind this makes the mock behaviour stop working for the deposits page.

Remove update token

---

src/App.tsx
src/api/wallet/WalletApiImpl.ts
src/api/wallet/WalletApiMock.ts
src/components/UserWallet/WalletComponent.tsx
src/components/UserWallet/index.tsx
src/hooks/useWalletConnection.ts
src/types/index.ts

Smaller delay in autoconnect allows to load UserWallet after autoconnect has done its work
Avoids layout thrashing and re-rendering
Also made `getWalletInfo` public to allow sync requests when initializing state in `useWalletConnection`
Avoids even more re-rendering

Suspended user wallet

---

src/api/index.ts
src/api/wallet/WalletApiMock.ts

`main.a4c5.js   781 KiB` >> `main.026c.js   778 KiB`
Change is minimal but this is the correct usage for tree shaking

fix inline env.vars

---

package.json
src/api/deposit/DepositApi.ts
yarn.lock

Uses the updated version of dex-js: https://github.com/gnosis/dex-js/pull/44
For the web, not much change is needed, only that we can make use of the exported and typed ABI

Update to last version of dex-js

---

src/components/TradeWidget/OrderDetails.tsx

Closes #347 
Doing this issue I realized that the formatting of the price was redundant, so there's a second PR for making a new util and refactoring between the trade widget and the orders:
* https://github.com/gnosis/dex-react/pull/398

Add more decimals to order details

---

src/components/OrdersWidget/OrderRow.tsx
src/components/TradeWidget/OrderDetails.tsx
src/utils/format.ts
yarn.lock

* Creates a format price function
* Refactor between orders and trade details regarding the format of the price
* It leaves for decimals as a default
* Improves https://github.com/gnosis/dex-react/pull/397 
Doesn't include: any styling. With more decimals, the rows are a big broken. I can easily fix this, but @W3stside is working on the styling of the orders and I want to separate the 2 PRs to avoid any conflict.

Calculate price

---

src/api/deposit/DepositApi.ts
src/api/erc20/Erc20Api.ts
src/api/exchange/ExchangeApi.ts
src/api/gasStation.ts
src/api/index.ts
src/api/wallet/WalletApi.ts
src/api/wallet/WalletApiMock.ts

fetch **gasPrice** from gas station
only fetch when network or block has changed, cache otherwise
Maybe a better place for this logic would be in the upcoming Cache Layer. Then it could add `gasPrice` to `txOptionalParams` and pass onto the real `api.method`:
```ts
// in cache layer method
// only if method will send tx, not a call method
const txOptions = {
...txOptionalParams,
gasPrice: await fetchGasPrice(),
}
api.realMethod(args, txOptions)
```
Closes #348

Gas station

---

src/api/wallet/WalletApi.ts
src/api/wallet/subscriptionHelpers.ts

Smart interval as an alternative subscriptions
Because mobile wallets generally don't support `newBlockHeaders`

Subscription alternative

---

src/html/index.html

Currently when `window.location` is detected as belonging to IPFS we use HashRouter instead of BrowserRouter
Detection relies on matching `Qm<hash>` with `location.pathname`
If the app is hosted on EthDNS at `<domain>.eth.link` that detection fails and we can't start browsing at a non-index route, also can't refresh the page at a subroute
This PR adds detection for `location.hostname`

Detect <doman>.eth.link  as IPFS

---

src/api/wallet/WalletApi.ts
src/api/wallet/subscriptionHelpers.ts

More comments for subscriptions helpers, as they are reportedly hard to read
In a sentence what happens is:
1. We want to sub to `newBlockHeaders`
2. We try to do it through `web3.eth.subscribe('newBlockHeaders')`
3. Works -- great
4. Doesn't -- start checking if block number changed on interval (supposed to be efficient, MMask does exactly that)
5. When changed, fetch new block
Also removes `interval`, which isn't used anyway, forgot to delete

Comments for subscriptions helper

---

src/components/DepositWidget/Row.tsx
test/components/DepositWidget.components.test.tsx
test/data/exchangeBalanceStates.ts

Closes #407 
* Allows to withdraw even if the token was not enabled.
* The "Withdraw" button is only shown if the user has a balance (no other condition is required)

Add balance for an unapproved token

---

src/components/ThemeToggler.tsx

localStorage stick around across page refresh, as a result dark mode stays even when auto is chosen
To reproduce:
1. Select dark mode
2. Select auto
3. Refresh page

Fix auto dark mode

---

.babelrc
package.json
yarn.lock

Workaround from an issue in [react-forntawesome repo](https://github.com/FortAwesome/react-fontawesome/issues/70#issuecomment-486626761)
This effectively changes 
```ts
import { iconName } from '@fortawesome/free-solid-svg-icons';
// to
import { iconName } from '@fortawesome/free-solid-svg-icons/iconName';
```
BEFORE:
AFTER:

Fornawesome bundle size workaround

---

package.json
webpack.config.babel.js
yarn.lock

Use one version of `bn.js` everywhere. Shaves off 3.5 Mb. Doesn't seem to break anything, though potentially could.
BEFORE:
AFTER:

Consolidate bn.js dependency

---

src/const.ts
src/hooks/usePlaceOrder.ts

Closes #459 
1. Create a new liquidity
2. Send the transaction
3. Using metamask, keep the tx confirmation window open
4. After 5 min, confirm the tx
- On a version without the fix, tx failed https://rinkeby.etherscan.io/tx/0x4df9101bf5dc15acfaaa76c8fc831820b76564c0d677dfe09aa65837b2cb1c13
- On version with the fix, tx succeeded https://rinkeby.etherscan.io/tx/0xa8258c29e1e7371f2fc8b4c1501c563bc8ac7e46beea4e8593d209eb88785e54

ValidFrom orders have now a wait period when no value is set

---

src/components/OrdersWidget/index.tsx
src/components/PoolingWidget/index.tsx

Closes #464
Remove for now the buttons in the orders page. They are a bit redundant. Flagged in the user test sessions
Also, removed the "Learn more about liquidity" links for now (until we have the devportal)

Remove "learn more about liquidity" links

---

package.json
test/api/ExchangeApi/TokenListApiMock.test.ts
yarn.lock

Per title.
You'll see now sUSD on deposit, trade and liquidity pages:

Updating dex-js to 0.1.8

---

src/api/exchange/ExchangeApi.ts
src/api/exchange/ExchangeApiMock.ts
src/api/exchange/utils/decodeAuctionElements.ts
src/const.ts
test/api/ExchangeApi/ExchangeApiMock.test.ts

Part of #455 
Implemented `getOrdersPaginated` corresponding to the contract's https://github.com/gnosis/dex-contracts/blob/master/contracts/BatchExchange.sol#L479
- `pageSize` is optional defaulting to `10`
- returns an object with `orders` and -- when there might be a next page -- `nextIndex`

Adding getOrdersPaginated method to ExchangeApi

---

src/components/PoolingWidget/index.tsx

Part of this taks https://github.com/gnosis/dex-react/issues/495
I took the simpler approach, I think :) 
We just keep a list of tokens for the liquidity page. The list is maintained there. It looks straightforward and good enough
If in the future we need more fancy stuff we can reevaluate

Filter tokens not in the liquidity list

---

src/hooks/useQuery.ts

`useQuery` doesn't update when `location.search` changes
Luckily it doesn't break anything as the source of truth after the first load is the form, but it potentially could
See reproduction gif where `sellAmount` stays the initial value

fix useQuery updates

---

src/hooks/useOrders.ts
src/reducers-actions/orders.ts

`useEffect` is run when deps changes
That includes on mount/unmount
So 
```
useEffect(() => {
forceOrdersRefresh()
dispatch(overwriteOrders({ orders: [] }))
}, [userAddress, networkId, forceOrdersRefresh, dispatch])
```
Would run and `forceRefresh` whenever we mount `OrdersRow`
One solution is to skip first run.
Another could be to centralize forceRefresh somewhere in global state near Provider, but then we would fetch even when we don't need to display orders
aside: setState is batched by default inside `useEffect` and in sync event handlers. some time in the future, with concurrent mode, will be batched everywhere

Fix refetch from 0 on mount

---

src/api/index.ts
src/hooks/usePlaceOrder.ts

Closes #511 
No longer able to place orders using tokens that are not registered in the exchange:
Works when 1 or both tokens are not registered.

When a token is not registered in the exchange, do not allow the order to be placed

---

src/html/index.html

Start with `<base href>` prefilled
No extra request to wrong uri
Nothing changes for ipfs deployment (still extra request)

Eliminate first request to /trade/vendors*.js

---

src/components/OrdersWidget/OrderRow.styled.ts
src/components/OrdersWidget/OrderRow.tsx

Closes #484 
Slightly different than requirement on #484 to be inline with current design.
Rather than filled/unfilled, displaying filled/total amount:
- Last column is still static

Added total amount to orders page

---

package.json
src/components/Portal.tsx
src/components/Tooltip.tsx
src/components/TradeWidget/TokenRow.tsx
src/hooks/usePopper.ts
yarn.lock

Adds
- Hook for Popper.js
- Hook with reasonable defaults ready to plug-n-play
- TooltipComponent for easy plug-n-play tooltips
- Sample tooltips on `/trade` page (style pending)
Tooltips don't have to look like that or like anything really, can be whole components inside

Tooltips sample integration

---

src/components/TradeWidget/index.tsx

Expands "Your orders" by clicking here:
So it shows a expanded version of the orders:
Related to https://github.com/gnosis/dex-react/pull/582

Expand your orders

---

src/components/TradeWidget/FormMessage.tsx
src/components/TradeWidget/InputWithTooltip.tsx
src/components/TradeWidget/TokenRow.tsx
src/hooks/usePopper.ts

Simplifies FormMessage component
Enables to use tooltips with <inputs> already hooked to form-hook

Tooltips for form input + extra

---

src/Console.tsx
src/components/DepositWidget/Row.tsx
src/components/DepositWidget/index.tsx
src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/index.tsx
src/components/PoolingWidget/index.tsx
src/components/Tooltip.tsx
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx
src/components/UserWallet/WalletComponent.tsx
test/hooks/useSafeState.hooks.test.tsx

`<button>` without explicit type is `type="submit"` by default
So any such `<button>` inside a form submits that form
Added explicit type to every button I found, let's do it explicitly from now on

Fix form submission

---

src/components/OrdersWidget/OrderRow.tsx

There was a hidden column in the orders that was not used :) 
Removed from the code
That's what it used to do:

Delete unused column

---

src/components/DepositWidget/Form.tsx
src/hooks/useKeyDown.ts

Adds a hook to call callback on keydown
Uses it to close Deposit/Withdraw from on /wallet page
Modali already has that functionality, so no need there
Closes #629

Close form on Escape

---

src/styles/global.ts

When opening Modali modal from Withdraw modal (when overriding withdraw request) screen briefly flashes
Happens because Withdraw modal has it's own overlay (not really overlay, but box shadow), so what actually goes on is:
1. Withdraw overlay on -> overlay background darkish
2. Withdraw off -> no overlay -> white background
3. Modali on -> overlay background darkish
A proper fix would be to change not modals but content of one modal: Form -> Modali contents,; without changing overlay in-between
Candidate for refactor? Candidate for refactor!

Fix for modali screen flash

---

src/components/PoolingWidget/index.tsx
src/components/TradeWidget/index.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/UserWallet/WalletComponent.tsx
src/components/UserWallet/index.tsx
src/hooks/useConnectWallet.ts
src/hooks/usePlaceOrder.ts

Follow up to #588 
When user is logged and tries to submit an order, the wallet dropdown is shown over the trade page.
- ~~There's a bug on `onSubmit` where the form data is not being passed down onto `data` object. To test I manually set the values. I guess this will be fixed by https://github.com/gnosis/dex-react/pull/551 so I didn't spend time trying to fix it. For this reason, you'll have to trust me it works or test locally.~~
- ~~It seems like the wallet widget is re-rendered every second, guess due to the batch time remaining thingy. Still have to check that.~~ Yep, that's the case.
- ~~For a reason that I yet haven't figured out, the wallet dropdown is expanded after logging in.~~

Triggering wallet connection from trade page on submission

---

src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/OrdersWidget/index.tsx

The redesign has a different name. It should be called "closed", nor "expired"

Change tab name to closed

---

src/components/TradeWidget/OrderValidity.tsx

when manually setting `0` values for both `validFrom` and `validUntil` the app wasn't setting the toggle on the checkboxes - WELL now it does

OrderValidity modal sanitization logic

---

src/components/DepositWidget/Form.tsx
src/components/DepositWidget/Row.tsx
src/components/DepositWidget/Styled.tsx
src/components/DepositWidget/index.tsx
src/components/DepositWidget/useRowActions.tsx
src/reducers-actions/tokenRow.ts
src/utils/transaction.tsx
test/components/DepositWidget.components.test.tsx

Deposit/Withdraw modals now close `onSentTransaction`. That is when user confirms transaction in the wallet.
To show tx in progress as modals are closed now there are spinners near values that will be updated
That's why there are individual sets to track claiming/withdrawing/depositing txs in progress
Closes #621

Non-blocking Deposit/Withdraw modals

---

src/components/DepositWidget/Form.tsx

So this is a quick fix and essentially a workaround
When Deposit/Withdraw modal opens in Chrome focus returns from the button just clicked to body
In Firefox it doesn't
That button swallows all onClick/KeyDown and doesn't let it bubble because react catches it, normally wouldn't prevent anything, or I think that's what happens
If we explicitly move focus bu clicking somewhere it works. Also it makes sense to just autofocus input

Fix Firefox Escape keydown

---

src/components/TokenSelector.tsx
src/components/TokenSelectorComponents.tsx

Prevents closing select Menu on Enter when no options displayed
Super hacky :robot::zap:

Fix close on invalid input

---

src/components/Layout/index.tsx
src/styles/global.ts

In general not a good idea to use `height: 100vh` as it doesn't account for scrollbar size.

Fix overflow undulating at 886px window width

---

src/components/PoolingWidget/CreateStrategy.tsx
src/components/PoolingWidget/index.tsx
src/const.ts

1. remove trailing zeros on SpreadInformation data
2. precision on liquidity spread input set to 6

Pooling interface input precision check

---

src/components/TokenSelector.tsx
src/components/TokenSelectorComponents.tsx

Addressing points missing on https://github.com/gnosis/dex-react/pull/597
Tried to use the example provided in this issue https://github.com/JedWatson/react-select/issues/3111
What I couldn't make work yet:
- ~Focus on search input~
- Placeholder text display fully
- ~Close button on title~
- List of tokens displayed over modal
- ~Build failing due to TS issues with `useRef` typings~
- ~(After merge with `0.9.0`) Enter on invalid selection loses focus to price input if any is unfilled~
Everything else (besides the horrible styling) work fine
Current looks:

Added custom react-select component for new styling

---

src/components/OrdersWidget/index.tsx
src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/Price.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

Gives all inputs in TradeWidget natural same tabIndex (when tabIndex the same, tabs go in DOM order)
I't not very apparent when some buttons are active, maybe we should style `:focus|:focus-within` for them
Orders validUntil modal was opened with Space in preview, so as not to break the index order
Closes #603

tabIndex order in /trade

---

src/components/TokenSelectorComponents.tsx

Original check was for a specific `displayName` of a child component.
That name as all the others was mangled and minified in production
Check proposed here looks at children of that child component, which comes from
```ts
// TokenSelector.tsx::L255
const noOptionsMessage = (): string => 'No results'
```
Still ugly but more robust

Fix focus stealing in production

---

src/components/DepositWidget/index.tsx
src/components/Layout/Card/Card.tsx
src/hooks/useDebounce.ts

Adds logic for filtering tokens and hiding tokens that have 0 in all balance columns
in /wallet page
Closes #612, closes #613
<sup>have to write twice for github to auto-close both</sub>
This is a unique PR in that it closes two issues at once, first of its kind.

Tokens search+hide

---

src/api/index.ts
src/api/thegraph/TheGraphApi.ts
src/api/thegraph/TheGraphApiProxy.ts
src/const.ts
src/services/factories/getPriceEstimation.ts
src/services/factories/index.ts
src/services/index.ts

Implementation of TheGraphApi for now only querying the prices.
Implementation of `getPriceEstimation` service.
Using Dima's suggestion, `getPrices` query for multiple prices at once, and `getPriceEstimation` service query for all known tokens at once as well for caching all prices locally.
Open for feedbacks and suggestions regarding this approach.
In another PR, will implement `usePriceEstimation` hook and add it to the interface somehow.

TheGraphApi and getPriceEstimation service

---

src/components/TokenSelector.tsx
src/components/TokenSelectorComponents.tsx

`react-select` was already changing active option on `ArrowUp|Down`, it just wasn't visibly styled
This PR also takes care of the recurring issue of `scrollTop` which happens when `menuList` overflows and selected element changes from the last to first.
Can check the behavior if you press `ArrowDown` long enough in develop.
As I understand when `menuList` determines how much to scroll it takes measurement  of the whole `MenuList` components and count from Top, but as we added our search component there top got moved.
By moving our custom elements above the `boundingRect` of `MenuList` , default `MenuList` is once again flush with custom `MenuList` dimensions..
Closes #741

Select with arrows

---

src/utils/validation.ts

Closes #752 
Validation prevented a new key to be pressed because the input was invalid, but input was already invalid in the first place.
This change allows invalid inputs to be cleared.

Updating validation to not prevent default in case input is not valid

---

src/api/thegraph/TheGraphApi.ts

Changes on https://github.com/gnosis/dex-subgraph/pull/33
`priceInOwl` field was replaced by `priceInOwlNumerator` and `priceInOwlDenominator`.

Adapting to TheGraph model changes

---

src/components/TradeWidget/index.tsx
src/const.ts
src/hooks/usePriceEstimation.ts

Part of #757 
Prices are reset even when a token pair has no price estimation.
This is no longer an issue. Leaving for future reference.
~One caveat is that one use case the price won't be updated, when it meets this conditions:~
- ~Price is set on the URL~
- ~One of the tokens in the URL doesn't have a price~
- ~The user picks different tokens, without changing the one without price.~
~Example:~
- ~Starting URL: `/trade/GUSD-SNX?price=10`~
- ~Token without a price: `GUSD`~
~1. Load the page~
~2. Switch `SNX` by any other token~
~Price will remain `10`~
~In that case, the price won't change UNTIL the _priceless_ token is swapped out. First time this happens price will work as expected.~
~3. Switch `GUSD` by any other token~
~Price will be updated~
~4. Switch back to `GUSD`~
~Price will be …

Reseting prices when switching tokens even if estimation is null

---

src/api/index.ts

Update TheGraph endpoint to use production.
Still indexing 👍 
It'll be updated soon:
https://thegraph.com/explorer/subgraph/gnosis/dfusion

Use production endpoint for the graph

---

src/components/EtherscanLink.tsx
src/pages/About.tsx

Adds a link to dune analytics
Also, link to the smart contracts
As a bonus I had to fix the Ethescan link component, cause the `networkId` was being used as a default, instead of being set as the network you want. So you could not use a different network than the one you are connected with your wallet. 
I reviewed and we were not using the `networkId` param anywere, so I think it's safe to change the behaviour. I added an aditional optional parameter for `networkIdDefault` in case we need the old behaviour

Add dune link, fix a broken link, and include smart contract addresses

---

src/api/tokenList/TokenListApi.ts

List of tokens were being concatenated with previously saved list of tokens from localStorage, making it quite large...
Here I do a simple 'merge' by only using unique addresses and ignoring repeated entries.

Merging both lists of tokens to avoid duplicates

---

README.md
src/assets/md/FAQ.md
src/components/PoolingWidget/StepDescriptors.tsx
src/pages/About.tsx

Updates the URL of the dev portal as asked by @c3rnst . 
It changed to https://docs.gnosis.io/protocol

Update URL dev portal

---

src/components/TokenSelector.tsx

We can change NoOptionsMessage dynamically to give user hints that a token can be added
Can even do 
but will be hacky and will have to rewrite `useAddTokenModal` logic a lot
Let's first discuss UX across all ways to add a token

No options message change

---

src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/TradeWidget/index.tsx

Closes #823 
Changes setup of `overflow-y: scroll` onto `.orderContainer`

Orders widget - keep order tabs visible

---

src/api/exchange/ExchangeApi.ts
src/api/exchange/ExchangeApiMock.ts
src/api/index.ts
src/api/proxy/CacheMixin.ts
src/api/tokenList/Subscriptions.ts
src/api/tokenList/TokenListApi.ts
src/api/tokenList/TokenListApiMock.ts
src/const.ts
src/hooks/useTokenList.ts
src/services/factories/index.ts
src/services/factories/tokenList.ts
src/services/helpers/getErc20Info.ts
src/services/index.ts
src/utils/miscellaneous.ts
test/api/ExchangeApi/TokenListApiMock.test.ts

Part of #467 
See title.
Also, removing tokens which don't exist for given network. Example:
Querying sequentially, nice and easy, nothing fancy parallel extra optimized etc.
And, no need for throttle after all...

Dynamically loading tokens ids, per network, first time getTokens is called

---

src/App.tsx
src/components/OrderBookWidget.tsx
src/pages/OrderBook.tsx

Part of #791
I would like to create as mentioned in #791  a placeholder so Felix can work on integrating his order book.
his PR includes:
- A new page with the selectors logic
- A new component for the Otherbook
- Add a wrapper with some example CSS --> just to show how to add CSS, but Felix pls remove the CSS in the next PR
Test it by navigating to `/book` address:
* http://localhost:8080/book
* https://pr800--dexreact.review.gnosisdev.com/book

Add order book page

---

src/html/index.html

Redirects to `https` whether server supports it or not
Reasons for -- some wallets don't work on insecure origins, like Opera wallet and Wallet Connect
Also, `http` is a bad idea in general
Why in `index.html`?
Because should do it as early as possible, before browser starts fetching, every resource will be redownloaded from new origin anyway
Closes #816, closes #828

redirect to https

---

src/components/TradeWidget/OrderValidity.tsx
src/components/TradeWidget/validationSchema.ts
src/const.ts

Closes #808 
OrderValidity - ASAP/Unlimited checkbox behaviour
1. auto focuses and selects content inside inputs on un-checking ASAP and or unlimited
2. undefined value auto checks ASAP/Unlimited

Order validity asap unlimited tweak

---

package.json

There's an issue with using CSS in the tests because the path to the mock JS is wrong.
I saw this in other branch, it only broke cause I included modali (which imports CSS) in the row component which that contains tests. I assume we never attempted a import of CSS before in a test :)

Fix path for to the fileMock in the tests

---

src/components/TokenOptionItem.tsx

Minor style touch up.
Noticed an issue, after parsing the custom address, and closing the token selector, some margin/padding seems gone here:

Style touch up.

---

src/api/proxy/SimpleCache.ts
src/components/TokenOptionItem.tsx
src/hooks/useAddTokenModal.tsx
src/services/index.ts

Try with `0x1d9a3cef66b01d44003b9db0e00ec3fd44746988` on mainnet, for example
I'm not a fan of how `react-select` resets input on `blur, then focus back`, but that's a separate issue

Token preview for register

---

src/components/TradeWidget/index.tsx
src/hooks/useTokenBalances.ts

Can't use `networkIdOrDefault` everywhere after all
Fixes
```
[useTokenBalances] Error for ...
```
on rinkeby

Fix wrong addresses on rinkeby

---

src/api/wallet/WalletApi.ts
src/hooks/useTokenList.ts

Even after numerous workarounds by me and @alfetopito  the problem remained
Problem is stemming from the fact that oftentimes on network change `newBlockHeaders` fires first, before `onNetworkChanged`. Sync nature of `useTokenList` didn't help either.
So we get stale network in `WalletInfo`
This solution is hacky, but so is the problem

Fix 875 token address on rinkeby

---

src/components/Input.tsx
src/components/InputWithTooltip.tsx
src/components/PoolingWidget/DefineSpread.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx

We agreed on removing the tooltips for the trade widget, they are too intrusive
This PR:

Remove tooltip in trade widget

---

src/components/OrderBookBtn.tsx
src/components/OrderBookWidget.tsx

I left this commit/branch unpushed, pushing now :) 
Mainnet:
Rinkeby:
If you are in a testnet (Rinkeby) and you are not very aware, the Order Book can be weird, because it uses the data from the smart contract in that network.
To make it more clear, I just show the name of the testnet if we are in a testnet, otherwise I don't show the name of the network (implying mainnet)

Order Book: Show network name for testnets

---

src/components/TokenOptionItem.tsx
src/components/TokenSelector.tsx
src/components/TradeWidget/index.tsx
src/hooks/useBetterAddTokenModal.tsx

~Not entirely happy with it~
try adding `0x45804880De22913dAFE09f4980848ECE6EcbAf78` in TokenSelector on mainnet
~breaks when wallet not connected for some reason~
`react-select` was overeager to react to every event, and also `SearchItem(NoMessageOption)` was unmounted before some logic could run in `Modali`

Confirmation in token selector

---

src/api/index.ts
src/const.ts

Let's not use Dima's API key anymore, once this is in production is a good idea Dima to delete you leaked API key. Thanks for borrowing it to us until now :) 
* It uses the API key devops made for us
* It uses an optional env var for the API key and for the URL. Is not used, but it's just a convenient way to be able to change the URL without generating a new version
Closes #871

Update infura key and set some env vars

---

src/components/OrderBookWidget.tsx

The current order book looks like this:
This PR is a proposal to remove the "Volume" and just show the "Accumulated volume" like in this picture:
The "plain Volume" is the sum of orders at that price point (not the sum of that price point and all better price points). Imo, the "plain volume" is not super relevant and make the UX more confusing. It was very confusing for me that the "Volume" was not a monotonous function, so you could see that even if you go left in the bids, the volume can decrease. 
As a user, I'd be interested to get how much I can sell for a give price. So my understanding is that I only need the accumulated volume, that in this PR is renamed as just "Volume"
Additionally, as it can also be seen in the picture, this PR adds the currency for the volume. 
Units can …

Volume: Leave only accumulated volume in the tooltip

---

src/hooks/useOrders.ts
src/hooks/useTimeRemainingInBatch.ts

Fixes #909 (more of a workaround than a fix)
Causes rerenders only when needed
Doesn't check on every second but rather being smart about initial timeout + intervals
To test revert a369fb5 with helpful logs still included

Force resfresh on batch time

---

src/utils/format.ts

A pet peeve of mine.
Let's use literal notation for regexp when possible
- `new RegExp(string)` is useful when string is dynamically constructed
- `new RegExp(/reg_exp/)` is copy-constructed
- `/pattern/` is genrally prefered for static patterns
[Reference 1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Description), [2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Creating_a_regular_expression)

switch to literal regexp

---

src/components/TradeWidget/index.tsx

When switching from mainnet to rinkeby old tokens stay in TokenSelector even if they are not available on rinkeby
Same when starting on rinkeby with URL containing mainnet-only token
try https://dex.dev.gnosisdev.com/trade/DAI-PAN?sell=0&price=0&from=&expires=2880 on rinkeby
This PR adds a check for tokens from url on network change

Fix stale tokens

---

src/api/tokenList/TokenListApi.ts
src/services/factories/tokenList.ts

On load `USER_TOKEN_LIST` was overridden with tokens from **TCR**.
As a result if user previously added an extra token not in **TCR**, it would disappear on page refresh
[Related](https://github.com/gnosis/dex-react/pull/981#issuecomment-625725927)

Fix tcr override

---

src/components/Modal.tsx

Added default `.modali-body-style` padding to `ModalBodyWrapper`. Seems ok with other instances of  `ModalBodyWrapper`
Fixes #1020

Double claim modal style Fix

---

src/components/DepositWidget/Form.tsx
src/components/DepositWidget/Row.tsx
src/components/OrdersWidget/OrderRow.tsx
src/components/PoolingWidget/LiquidityButtons.tsx
src/components/Spinner.tsx
src/components/TradeWidget/index.tsx
src/components/UserWallet/WalletComponent.tsx
src/hooks/useBetterAddTokenModal.tsx

Refactor spinners into it's own component
Closes #844

Refactor spinners into a new component

---

src/api/wallet/composeProvider.ts

I couldn't connect some mobile providers(including TrustWallet)
My guess is that the minimal Provider interface that `eth-json-rpc-middleware/providerFromEngine` implements, which is only `send` and `sendAsync` functions, is not enough. Even if we reemit events
Maybe adding `enable` function would suffice. Maybe some more. I just wrapped `composedProvider` in a `Proxy`

Proxy composed provider

---

src/components/TokenImg.tsx

Fixing token images on dark mode

---

src/components/OrderBookBtn.tsx
src/components/OrderBookWidget.tsx
src/components/TradeWidget/Price.tsx

Fixes #1056
This PR does a refactor in the Order Book to tackle with the following issues:
- All operations are done using floats, so there's some precision errors and possible overflows
- The order book continues to be a source of confusion
- A refactor will come handy to prepare for https://github.com/gnosis/dex-react/issues/1049
- It prepares for receiving `string` from the API instead of numbers --> I guess that's coming, since Nick is working in the event-base order book. Now if they send strings instead of numbers, it should work too
Apparently we were showing the order book the other way around
If we sell `USDC` for buying `WETH`, then we are in  `WETH-USDC` market
* `WETH`: Base token
* `USDC`: Quote token
This PR corrects this issue in the trading page
It was source of confusion. …

Improve order book representation

---

src/components/FileDownloaderLink.tsx
src/components/TradesWidget/TradeRow.tsx
src/components/TradesWidget/index.tsx
src/utils/csv.ts

Adds CSV saving functionality
Feel free to style/position as you see fit
Also I'm not a fan of how `formatTradeAsCSV` has to duplicate a lot of `TradeRow` functionality and make an extra loop over `trades`.
Maybe perform formatting only once and make `TradeRow` accept
```js
[
displayTokenSymbolOrLink(trade.sellToken) + '/' + displayTokenSymbolOrLink(trade.buyToken),
formatSmart({ amount: trade.sellAmount, precision: trade.sellToken.decimals as number }) +
' ' +
displayTokenSymbolOrLink(trade.sellToken),
formatPrice(trade.limitPrice),
formatPrice(trade.fillPrice),
formatSmart({ amount: trade.buyAmount, precision: trade.buyToken.decimals as number }) +
' ' +
displayTokenSymbolOrLink(trade.buyToken),
classifyTrade(trade),
new Date(trade.timestamp).toLocaleString(),
trade.txHash, …
```

Save trades as csv

---

.nvmrc
package.json
webpack.config.babel.js
yarn.lock

Sorta fix, please try on different machines on node v12
IPFS hash of `dist` ~QmNc3PH6sup1S324Vy7n45c7PEUyT71xWuFQpytmBxbM9Y~
`QmcyAq4hcixRUN7HTKf2jXD37HpHBSoauvPDGygJqGixkh`
My `ls -1 dist/` 
<details>
<summary>List</summary>
```
0dda5618c0d71a913ff55ddfe1a9556f.svg
175a9fc03995fdcd4071a4b6cf6d729f.svg
6407f8f1e2b66fe534e67c00522e9a42.svg
6ddcce99d9ec12220e0f78621130bb81.svg
70e1546cb31f915982f5ca933e111a0d.svg
7233bf7efb01021a1c99efa0349c7440.svg
8f446b386d6210378636576cea38faed.png
9a3038b98e535f97fae2d630d1c9a82f.svg
assets
autoconnect_chunk~f9abe98c.118a820016de8b28d159.js
autoconnect_chunk~f9abe98c.118a820016de8b28d159.js.map
ca51f1b062e5fac0c9c8e6723f916b0f.svg
cbebdb195faa8383b5246c50a369c5ad.svg
d59af6af2f821c0b95d35e65454755ac.svg
detect-browser~67af1680.f600d7ef6faf90c13e2e.js …
```

Stable hash fix

---

src/components/OrdersWidget/OrderRow.tsx

`Filled` status takes precedence over `Expired`

---

src/components/TradesWidget/TradeRow.tsx

Uses inversePrice inside `Limit/Fill Price` in `Fills`
**Was**:
**Now**:

Show inverse price in Market (Fills)

---

src/components/TradesWidget/TradeRow.tsx
src/utils/display.tsx

Reverses the market computation for filtering: WETH/DAI is now filtered by DAI/WETH etc

reverse market computation

---

src/api/exchange/ExchangeApi.ts
src/components/OrdersWidget/index.tsx
src/components/TradesWidget/TradeRow.tsx
src/components/TradesWidget/index.tsx
src/hooks/useOrders.ts
src/hooks/useTrades.ts
src/utils/display.tsx
src/utils/filter.ts

Closes #1118
Test:
1. head to /orders or on /trade
2. search via:
a. WETH-TUSD
b. WETH/TUSD
c. WETH TUSD
d. (`/orders` and/or `Active` | `Liquidity` | `Closed` tabs only): 
i. WETH-TUSD (or variations with "/" or " ") and the inverse market too: TUSD-WETH
Query: <sellToken>[SEPARATOR]<buyToken>

Filter /Orders by market

---

src/components/TradeWidget/Price.tsx
src/components/TradeWidget/index.tsx

Displays only reverse price filed, that is BUY/SELL by default
Also changes `BUY/SELL`  to `SELL per BUY`
Allows to swap between `SELL per BUY <-> BUY per SELL`
Related to #1132

One price field

---

src/const.ts
src/hooks/useTokenBalances.ts
src/utils/miscellaneous.ts

Instead of a hard value of max uint128, we now check
whether allowance is >= 10**(token.decimals + 12)
The assumption we had before did not hold for DMG token.
We set the allowance to maxint256, but on their contract the amount is downcast to utin128 (https://etherscan.io/address/0xed91879919b71bb6905f23af0a68d231ecf87b14#code)
So doesn't matter how many times the allowance is called, the UI still considers it as not enabled.
1. Enable DMG in mainnet https://dex.dev.gnosisdev.com
Refresh the page.
Should still show the `Enable` button.
2. Check DMG balance on https://pr1147--dexreact.review.gnosisdev.com/wallet
Should show the `+` sign

Updating how we calculate whether a token is enabled.

---

README.md
config-default.yaml
src/api/wallet/WalletApi.ts
src/const.ts
src/types/config.ts
src/utils/autoconnect.ts

Adds a new config for wallet connect bridge
Changes also the default to use Gnosis one, since it's more reliable
@nlordell , let me know if this solves your issue

Wallet connect bridge

---

src/api/exchange/ExchangeApi.ts
src/components/DepositWidget/Styled.tsx
src/components/DepositWidget/index.tsx
src/components/Layout/Card/Card.tsx
src/components/OrdersWidget/OrderRow.styled.ts
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/OrdersWidget/index.tsx
src/components/TradesWidget/TradeRow.tsx
src/components/TradesWidget/index.tsx
src/components/WrapEtherBtn.tsx
src/hooks/useOrders.ts
src/hooks/usePendingOrders.ts
src/utils/display.tsx
src/utils/filter.ts

Merges into #1096 
Optimises CSS
`/trades` formatting was a bit strange due to `CardWidget`s default CSS which was optimised for `Balances` page
a. edited to better fit 
Added `isTab` prop to `TradesWidget` to optimise column sizes for both formats
Standardised `thead` size across all tables
**Waterfall PRs**
1. adds filtering for `trades` aka Fills
2. uses inverse price for fills widget/tab
3. adds market filtering e.g `WETH/DAI` or `WETH-DAI` or `WETHDAI` and inverse (inverse search only for `Active/Liquidity/Closed` orders, not for fills
4. css fixes on table styling etc

1029.2/david style take

---

src/components/TradesWidget/index.tsx
src/hooks/useTrades.ts
src/reducers-actions/trades.ts
src/utils/miscellaneous.ts

- Now working 100% :+1: 
- Addressed edge case with pending trades causing duplicates errors all over the place
- Working internally with sets/maps, transforming during serialization/deserialization
- Keeping track of all trade ids on global state to avoid duplicates and not need to go through the whole list of trades on every update.
----
Fixing bug reported by Anxo regarding pending trades and JSON serialization/de-serialization of Maps.
Still getting some duplicates. Using Sets to try and avoid that but didn't help much.
Will spend more time on this next Monday.

Trades localStorage fixes

---

src/api/wallet/composeProvider.ts

Hack for easier debugging from an arbitrary account's perspective
`window.loginAs('0x1234ef...')` to enable for account
call `window.loginAs('')` with anything falsy to disable
Read-only access obviously, no sending txs.
Development only.

Substitute acc

---

src/components/TradesWidget/TradeRow.tsx
src/const.ts

Date displayed for a trade was based on batch time, which is the start of the 5min interval.
It's misleading though, since in fact the trade happens up to minute 4 of the batch.
So when the trade is actually detected, it' shows as having happened 4min+ ago.
With this change, the time displayed is the transaction timestamp of when the solver executed the trade.

Using transaction time instead of batch time for trades date

---

src/components/TradeWidget/OrderValidity.tsx
src/hooks/useQuery.ts

Closes #1131 
Some changes somewhere changed the modal closing behaviour and was sanitising `undefined` values indicating `ASAP` or `Never` ending orders back to `0` which fail form validity checks
To test: in url remove either or both `from=` &/or `expire=` or set as shown and check order submits. Also click the gear icon to set custom times and try clicking ASAP and/or Never - modal should close no problemo

fix ordervalidity input sanitzation when ASAP/Unlimited

---

src/components/TradeWidget/index.tsx

When an order is submitted with `validUntil == NEVER` due to default values on the form it becomes 0
and `validUntilWithBatchID == validFromWithBatchID`, and `isPendingOrderActive` in the part of
```js
batchIdToDate(order.validUntil) >= now
```
marks order as inactive
So that pending order is put into [closed](https://github.com/gnosis/dex-react/blob/1fb0a3110e9ccc85bc013951e5669fa625fcec95/src/components/OrdersWidget/index.tsx#L72) category
This here be fix for that

Fix pending orders

---

src/components/WrapEtherBtn.tsx

Fixes #1166
We always ignore locale in inputs (in Deposit modal and on /trade max), but not in unwrap one

Fix locale ',' in input

---

src/api/wallet/composeProvider.ts

The app doesn't send currently the gas. It assumes the Wallet does the estimation of it.
This is the case for most of the wallets, but is not true for Trust Wallet, at least, it's not true any more.
In the past, Trust Wallet was working even if you don't provide the gas, not sure if it was GETH doing it for them, or they were actually doing it.
Checking the JSON RPC documentation I can see that, although it's OPTIONAL, the default is not that the node should estimate, the default is to use 90K.
For this reason it's important to provide the gas limit. This will solve many of the errors in Trust Wallet, and potentially other wallets.
This fix along is not enough for some of the issues reported by users. They also need to update to the latest Trust Wallet. At least, it was not enough in my …

Fix trust gas issue

---

src/components/TradeWidget/TokenRow.tsx

Closes #1193 
Disconnect wallet and check button isnt there

disable wrapEther on disconnect

---

src/components/OrdersWidget/OrdersWidget.styled.ts

Removing this fixes the issue in IOS.
Why would the form need a fixed height?
Before:
After:

Remove fixed height that breaks IOS

---

src/components/Layout/Header/index.tsx

Supersede https://github.com/gnosis/dex-react/pull/1212  so it contains a longer message:

Batch tooltip looooong

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts

Change GetPriceResponse type to correspond to dex-price-estimator

---

src/utils/autoconnect.ts

As part of #1199, we should try not to rely on deprecated API as much as possible.
This PR changes autoconnect logic to use `web3modal.connectors` to create providers for us.
And while internally the connectors call `provider.enable()` we can expect **web3modal** to eventually switch to `provider.request` method.

Don't call provider.enable() directly

---

src/components/TradeWidget/index.tsx

Closes #1225
Simple fix, prevents submission when either value is 0.
We had the check in place for `falsy` values, but since amount is a BN, we also need to check whether it's zero.
Does not address the slowness to fill in buyAmount.
Printing debug log entry when a null value is detected:
1. Fill in a sell amount
2. Click on suggested price
3. Very quickly, click on submit or hit enter.
Before: the wallet is prompted to sign the tx, before the `Receive at least` (buyAmount) is filled
After: no tx is sent, debug log message is printed.

Preventing submission when either sell/buy amount is 0

---

src/components/Layout/PageWrapper.tsx
src/components/Layout/index.tsx
src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/PoolingWidget/CreateStrategy.styled.ts
src/components/PoolingWidget/DefineSpread.styled.ts
src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/PoolingWidget/index.tsx
src/components/TradeWidget/Price.tsx
src/components/TradeWidget/PriceEstimations.tsx
src/components/TradeWidget/TokenRow.tsx
src/components/TradeWidget/index.tsx
src/styles/global.ts

Fixes some general css issues
1. make height relative/percentage for OrdersTable and dependent on entire wrapper, dont give height to both orders table and wrapper
2. fixes width of table when expanded
3. adds scroll to warning when too long (eliminates weird styling if user inputs some enormous number even with `formatSmart`)

Orders widget height fix

---

src/const.ts

Closes #1229 
This issue as been previously addressed on https://github.com/gnosis/dex-react/pull/1147 when a token used uint128 for allowance.
This time, the token uses uint96.
This change reduces the minimum amount required to consider a token enabled.
Using the COMP token as example, that has 18 decimal places, the user now will have to deposit over 29 billion COMP before an allowance refresh is required:
To test, add COMP token (`0xc00e94Cb662C3520282E6f5717214004A7f26888`) to your mainnet wallet and enabled it.
On latest mesa.eth.link after refresh the page, the enable button will be shown again.
On this PR, it won't.

Decreasing the amount of token required to consider token enabled

---

src/components/PoolingWidget/index.tsx

The issue happens because:
1. Page load
2. No connection => default networkId = 1
3. `selectedTokensMap` is filled with tokens from network 1
4. Connection to rinkeby established
5. Tokens updated
6. But `selectedTokensMap` not refilled
This is a quick fix, but let's switch to addresses instead of symbols soonish.
Having addresses in `LIQUIDITY_TOKEN_LIST` and that list differentiating by network would have made this issue more obvious (cause there would not have been a match for wrong address on the right network)
Closes #1235

Fix liquidity orders on rinkeby

---

src/components/OrdersWidget/index.tsx
src/hooks/useTabs.tsx

Creating component inside a hook is generally not a good idea. Causes remounting.
See how `<buttons>` disappear on each block instead of just being updated.
Can be solved with memoization.
Or by separating component from the hook.
Modali and react-hook-form use this same pattern:
```js
const [modalHook, toggleModal] = useModali()
...
<Modali.Modal {...modalHook} />
```
```js
const methods = useForm();
...
<FormProvider {...methods} > // pass all methods into the context
```

Use tabs outside

---

src/components/OrdersWidget/OrderRow.styled.ts
src/components/OrdersWidget/OrderRow.tsx

Removing duplicated `Market` row for responsive orders

---

src/components/TradeWidget/PriceEstimations.tsx

Small fix, this got changed during a refactor.
To be merged onto #1234 
Before:
After:

Token for price estimator is fixed, even when showing inverted price

---

src/components/OrdersWidget/index.tsx
src/components/TradesWidget/index.tsx

Fills tab was displaying `trades.length` before filtering unsettled and reverted trades.

Fix wrong Fills number

---

src/components/DepositWidget/index.tsx
src/components/TradesWidget/index.tsx
src/pages/Trades.tsx

Forgot to wrap TradesPage in the overflow wrapper... fixes that

Trades page styling

---

src/components/PoolingWidget/AddFunding.tsx

Liquidity orders now are displayed on `/liquidity` page
Before:
After:

Updated liquidity success message

---

src/pages/Orders.tsx

Mobile `Fills` tab shows all trades, regular and liquidity.
That's because on responsive mode we show `/orders` page directly.
This change enables the filter for the `/orders` page equal to the one used on `/trade` page.

Do not show liquidity trades on orders page

---

src/components/OrdersWidget/OrderRow.tsx

Just a tiny detail that bother me while testing and just went for it
Before:
After:
Before @Velenir says anything, `{' '}` don't work for me, cause prettier plugin turn it into a space, that then is removed when rendering. Old school `&nbsp;` works fine

Sepatate the spinner and Pending label

---

src/components/OrdersWidget/index.tsx
src/hooks/useSortByTopic.ts

Invert orders initial sort by date

---

src/api/gasStation.ts
src/api/wallet/WalletApi.ts
src/api/wallet/WalletApiMock.ts
src/components/TradeWidget/TxMessage.tsx
src/components/TradeWidget/index.tsx
src/hooks/useGasPrice.ts
src/hooks/usePriceEstimation.ts
src/utils/minFee.ts

Ignore styling, check logic only
Additionally, what would be the best way to get `MIN_ECONOMICAL_VIABLE_FEE_IN_OWL`:
1. as a fixed value
2. or calculate like in #1227
2.1. get ETH price In OWL from [market endpoint](https://github.com/gnosis/dex-services/tree/master/price-estimator#estimated-buy-amount)
2.2. => min economical viable fee = (120k gas)(40GWEI)(Etherprice in owl)=(120000 * 40 * 10**9 * 240 *1000) =1.2 OWL
Will the solver be run with `--min-avg-fee-per-order` as start-time flag (so a fixed fee), or will the fee be dynamic? @josojo

Low volume warning

---

src/utils/flagCodes.ts
webpack.config.babel.js

Setting env variables by default to `null` as per [EnvPlugin docs](https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values:~:text=To%20specify%20an%20unset%20default%20value%2C%20use%20null%20instead%20of%20undefined)
Though it doesn't make them _unset_ in the end, semantically fits

Fix EnvironmentPlugin warning

---

src/components/DepositWidget/Row.tsx
src/components/DepositWidget/Styled.tsx

Fixes #1294 
Broke on some very particular window sizes
BEFORE:
AFTER:

Fix css balance overflow

---

webpack.config.babel.js

```js
{
// ...
PRICE_ESTIMATOR_URL: process.env.PRICE_ESTIMATOR_URL || (isProduction && 'production') || 'develop',
// ...
}
```
Checks if `NODE_ENV=production` and sets `PRICE_ESTIMATOR_URL` accordingly
Tested it via `yarn build` then running `serve dist` and checking the URL in network - was `production`
Tested it via 1 time `yarn build:dev` aka `NODE_ENV=development <rest_of_build_script>` and the URL was `develop`

yarn build NODE_ENV production sets PRICE_ESTIMATION_URL to production

---

.travis.yml
webpack.config.babel.js

Travis was returning:
```bash
$TRAVIS_BRANCH = hotfix/* || \ $TRAVIS_TAG != "" ]] && \ echo "production" || echo "develop")
No command ' echo' found, did you mean:
Command 'echo' from package 'coreutils' (main)
Command 'aecho' from package 'netatalk' (universe)
echo: command not found
```
due to the `\` before echo
Changed to:
```bash
$TRAVIS_TAG != "" ]] && echo "production" || echo "develop")
```
Seems fixed:

fix travis yml price estimation setting logic

---

src/pages/About.tsx

Fix `<div> cannot appear as a descendant of <p>` in /about page

Fix html hierarchy

---

config-default.yaml
src/api/index.ts
src/api/tokenList/TokenListApi.ts
src/api/tokenList/tokenList.ts
src/types/config.ts
test/api/ExchangeApi/TokenListApiMock.test.ts

The app depends on an initial list of tokens in dex-js
This list is used for an initial warm up of the app, when there's no persisted local storage, and the TCR hasn't been loaded.
The list of tokens are the initial thing forks change.
Judging from other projects, they end up being super creative on how to hack this list into the app.
This PR tries to make it easier for them to add a custom list. So:
- adds `initialTokenList` config params, with this list
- Makes `getTokensByNetwork` in tokenList api to not depend on dex-js anymore. It just receives the list by parameter
- Modifies tokenList API to receive the list in the constructor
- Now the initialization of the APIs, load the list from the config, and inject it to the API

Allow to specify an initial list of tokens in the config

---

config-default.yaml
src/App.tsx
src/components/TradeWidget/index.tsx
src/types/config.ts

Brother PR of #1357, same motivation:
> The app depends on an initial list of tokens in dex-js
> This list is used for an initial warm up of the app, when there's no persisted local storage, and the TCR hasn't been loaded.
> The list of tokens are the initial thing forks change.
In this PR it's been added a new `initialTokenSelection` that allows you to set the default selection in the trade page. By default, we select DAI and USDC as the initial selection for sell token, and receive token.
One fork could, thanks to #1357 change the initial list, and then with this one, could change the initial selection (choosing 2 tokens from his custom list).

Allow to change the default initial selection of tokens

---

src/App.tsx
src/components/OrderBook.tsx
src/components/OrderBookBtn.tsx
src/components/TradeWidget/Price.tsx
src/components/TradeWidget/index.tsx
src/pages/OrderBookPage.tsx

- Removes the button that adds the orderbook modal
- Adds the orderbook in the main page
Additionally, note that it does to renamings/refactor:
- OrderBookWidget is now OrderBook
- OrderBook is now OrderBookPage
@Velenir @W3stside , not in this PR, but I would love to change all pages names, to have Page suffix. What do you think? I just changed the orderbook in this PR.

Show orderbook component

---

src/components/Layout/PageWrapper.tsx
src/components/TradeWidget/index.tsx

We have this weird edge case where if the user puts in an unknown token address/name or whatever the URL grabbing code defaults to market DAI/USDC - this allows users to potentially have the same market e.g DAI/DAI or USDC/USDC and we have an error code to deal
error message looked awful, fixes that
this is more of a pave over of a bigger problem but it looks better at least and users are blocked from doing anything until they change to a compatible token pair

fix error label if edge-case where tokens are the same

---

src/components/TradeWidget/TxMessage.tsx

An edge case when `priceEstimation = 0 --> minTradableAmount  = Infinity` for a token, happens when that token has not been traded yet.

Fix warning when priceEsimaion = 0

---

package.json
src/components/TradeWidget/index.tsx
src/components/TradeWidget/useNumberInput.tsx
src/hooks/useSubmitTxModal.tsx

`SubmitButton type="submit" ... >` now => `SubmitButton type="button" ... >` - should eliminate any race-conditions from form submitting vs confirmation modal popping up

TX Confirmation modal sometimes not popping up

---

.storybook/tsconfig.json
config-default.yaml
test/config.spec.ts
tsconfig.json

- Fixed `CONFIG.initialTokenList`
- Added tests
- 
- Added a separate `tsconfig` for `./.storybook` because putting `includes: [**]` into main `tsconfig` would require explicit mention of all folders to traverse. For example `tests`. Without `includes` all required folders were already included, but not `.storybook`. As I understand by default all folders in the rootdir are included bit not those that start with `.` Better to have one-for-all `tsconfig` at root, and one for the specific case of `.storybook`

Fix CONFIG.initialTokenList

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts
src/components/OrderBookWidget.tsx
src/pages/OrderBook.tsx

Convenience feature to see the orderbook at arbitrary points in the past. This only applies to the hidden orderbook page under http://localhost:8080/book
I'd really appreciate some styling help how to align this text box a bit nicer.
Also making sure that we can still load the normal orderbook at the most recent batch.

[HiddenOrderbook] Allow to fetch historic books by batchId

---

src/api/dexPriceEstimator/DexPriceEstimatorApi.ts
src/api/dexPriceEstimator/DexPriceEstimatorApiProxy.ts
src/components/TradeWidget/index.tsx
src/components/trade/LimitOrder/LimitOrder.tsx
src/components/trade/PriceSuggestions/PriceSuggestions.stories.tsx
src/hooks/useBestAsk.tsx
src/hooks/useTokenList.ts

Waterfalls into #1273 
Adds `getBestAsk` to `DexPriceEstimatorAPI` and cache
Adds `useBestAsk` hook similar to `usePriceEstimation` hook
API: `getBestAsk` URL looks like: `https://price-estimate-mainnet.dev.gnosisdev.com/api/v1/markets/1-7/estimated-best-ask-price?unit=baseunits&roundingBuffer=enabled`
With `?unit=baseunits&roundingBuffer=enabled` appended to end - any issues there?
Testing (in chrome console on localhost Mesa):
```js
(await dexPriceEstimatorApi.getBestAsk({ networkId: 1, baseToken: { id: 1 }, quoteToken: { id: 7 }})).toString()
```
Have to `invert` bestAsk BigNumber via `invertPrice` as:
estimatePrice endpoint returns:
==> **`0.0026...`**
while `bestAsk` enpoint returns:
==> **`358.29317033862816`**

DexPriceEstimator["getBestAsk"] + useBestAsk() hook

---

package.json

Simplifies the `package.json` so we don't have a script just for browserstack.
Also this way we can access the dev server from localhost or from our local network. This is convenient for access from our mobile using WIFI
Additionally, makes it coherent with storybook, which we already allowed:

Allow to connect from non-localhost

---

src/api/proxy/CacheMixin.ts

Using `CacheMixin` cached promise result of a method, but didn't change return type of that method.
So when you would expect `method()` to return a Promise and would call `method().then()` it would fail if returned from cache
This PR removes caching of Promise result. Still leaves in place cache invalidation for rejected promises.

Fix unwrapped promise cache result

---

.storybook/preview.tsx
package.json
src/App.tsx
src/api/dexPriceEstimator/DexPriceEstimatorApi.ts
src/api/dexPriceEstimator/DexPriceEstimatorApiProxy.ts
src/components/TradeWidget/TxMessage.tsx
src/components/TradeWidget/index.tsx
src/components/common/EllipsisText.stories.tsx
src/components/common/Frame.tsx
src/components/common/SwapPrice.stories.tsx
src/components/common/SwapPrice.tsx
src/components/layout/SwapLayout/SwapLayout.stories.tsx
src/components/layout/SwapLayout/index.tsx
src/components/layout/TradingLayout/TradingLayout.stories.tsx
src/components/trade/Price.stories.tsx
src/components/trade/PriceSuggestions/PriceSuggestionItem.tsx
src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx
src/components/trade/PriceSuggestions/PriceSuggestions.tsx
src/components/trade/PriceSuggestions/index.tsx
src/hooks/useMinTradableAmountInOwl.ts
src/storybook/LoremIpsum.tsx
src/storybook/RouterDecorator.tsx
src/storybook/decorators.tsx
src/utils/minFee.ts
test/utils/minFee.spec.ts

Waterfall PR depending on #1404 
----
This PR create the stories for the 2 layouts of the App:
* SwapLayout: Dapp v1.0
* TradingLayout: Dapp v2.0
It also: 
* moves the global styles to TradingLayout, since we don't have global styles for the v2.0
* Delete the global decorator for global styles in Storybook. Now the components look very neutral, which I think it's good thing! This should help with the redesign
v1:
v2:

Stories for layouts

---

src/components/layout/SwapLayout/index.tsx

Some users are scared :) 
BEFORE
AFTER:
I personally like it less 😢
but we don't want to scare people

Change skull for a warning sign

---

src/api/deposit/DepositApi.ts
src/api/erc20/Erc20Api.ts
src/api/exchange/ExchangeApi.ts
src/api/wallet/composeProvider.ts
src/api/weth/WethApi.ts

Adds some logs for when the estimation failed. 
It helped me now to debug an issue, I think is good to add. Also, now we also show the transaction details in the log even if we succeed on the estimation
Also, it adds logs at API level, for methods that send transactions

Add debug in case of estimation error, and when sending a tx

---

src/components/UserWallet/WalletComponent.tsx

The disconnect button doesn't work if you click on it.
This is because the onClick event was added only to the text, not to the button

Allow to click in any part of the disconnect button

---

src/api/wallet/composeProvider.ts

Workaround for issue with **WalletConnect** `request` method being called with Window context
Issue came with a regression in **web3** `RequestProvider`.

Explicitly not support provider.request

---

.storybook/main.js
src/components/common/TokenImg.tsx

When using `require.context` with our webpack config a required module takes shape of
```ts
{
default: "/5a86806e7c0681c126888fe301054197.png",
Symbol(Symbol.toStringTag): "Module",
__esModule: true
}
```
When using with storybook module becomes `'static/media/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d.5a86806e.png'`
Issue storybookjs/storybook#11610

Require(*).default storybook workaround

---

src/api/earmark.ts
src/api/wallet/WalletApi.ts
src/api/wallet/WalletApiMock.ts
src/api/wallet/composeProvider.ts

- Moves gas calculations into middleware
- Extra gas is calculated once per userPrint generation
As per [discussion](https://github.com/gnosis/dex-react/pull/1445/files#r494919850)

Earmark logic in middleware

---

package.json
src/api/tokenList/TokenListApi.ts
src/api/tokenList/tokenList.ts
src/components/PoolingWidget/CreateStrategy.tsx
src/components/PoolingWidget/SubComponents.tsx
src/components/PoolingWidget/TokenSelector.tsx
src/components/PoolingWidget/index.tsx
src/components/TokenOptionItem.tsx
src/components/common/SwapPrice.tsx
src/components/common/TokenImg.tsx
src/components/trade/LimitOrder/LimitOrder.tsx
src/components/trade/PriceSuggestions/PriceSuggestionItem.tsx
src/components/trade/PriceSuggestions/PriceSuggestions.tsx
src/hooks/useBetterAddTokenModal.tsx
src/reducers-actions/trade.ts
src/services/factories/getTokenFromErc20.ts
src/services/factories/getTokenFromExchange.ts
src/services/factories/tokenList.ts
src/services/helpers/getErc20Info.ts
src/services/index.ts
src/storybook/data/types.ts
src/types/config.ts
src/types/index.ts
src/utils/display.tsx
yarn.lock

Addresses #1442 
This is a big refactor of the types. 
There was too many Token definitions. Now most of the token definitions are in `dex-js`
Also, addresses one annoying thing, that we declared `TokenDetails` in dex-js and dex-react, making it super confusing.
Now TokenDetail is only in dex-react. 
dex-js has TokenDex (former TokenDetail) and these other definitions:
```
export type TokenErc20 = WithSymbolAndName & WithAddress & WithDecimals
export type Token = TokenErc20 & WithAddressMainnetOpt & Partial<WithId>
export type TokenDex = TokenErc20 & WithAddressMainnetOpt & WithId
```
Depends on dex-js `v0.7.2` that shoud be tagged as soon as we merge https://github.com/gnosis/dex-js/pull/187
Also, I leave this for other PR because is 100% independent of this one: …

Refactor and simplify token types

---

src/api/tokenList/TokenListApi.ts
src/api/wallet/WalletApi.ts
src/components/TradeWidget/index.tsx
src/components/TradeWidget/utils.ts
src/hooks/useWalletConnection.ts

When switching to xDAI chain and refreshing the page it would break with `symbol of undefined` error (@anxolin knows what I'm talking about). First experienced at https://pr1449--dexreact.review.gnosisdev.com/
That would happen because we cast TS types for `getToken` to `TokenDetails` when it could be `undefined`
When there are no tokens for the network (in `config.yaml` or elsewhere) `tokens` array becomes empty
So after adding xDAI tokens to config, the error would fix itself, but still not a good idea
This PR allows for `tokens = []` and as a side-effect allows to switch to an unsupported chain without the whole app coming down.
Try Ropsten, for example.

Fix xDAI token break

---

config-default.yaml
src/types/config.ts
test/config.spec.ts

Part of #1495 
Just adds the network specific token list details inside `CONFIG` and changes types as necessary

Config token list by network

---

src/components/OrdersWidget/OrderRow.tsx

Shows a spinner for order id in Pending Orders instead of a date timestamp

Pending Orders: Order ID shown now as Spinner (prev. date timestamp)

---

src/reducers-actions/pendingOrders.ts

Model the pending transactions state differently, so we don't assume, we let the thing be undefined
We received a bug report of that part, maybe a race condition. Still revieinging, but for now, let's not make the assumption

Account for pending orders being undefined

---

src/components/UserWallet/UserWallet.styled.ts

`top: -0.6rem` > `top: -0.8rem` crazy

userWallet network smushed fix

---

.eslintrc.js
src/api/index.ts
src/components/TokenOptionItem.tsx
src/components/TradesWidget/TradeRow.tsx
src/reducers-actions/orders.ts
src/reducers-actions/pendingOrders.ts
src/reducers-actions/trades.ts

Not having `switch case -- break`  broke #1517 This PR is so that doesn't happen again
- Adds `eslint:recommend` rules
- Fixes scoping in switch-case
- Fixes switch-case fallthrough
- Removes extra escaping in `RegExp`

More linter rules

---

src/components/OrderBookBtn.tsx

`useEffect` was triggered when unnecessary
Because tokens were recreated somewhere when they shouldn't have, which is a separate problem.

Fix orderbook tokens reset

---

src/api/tokenList/TokenListApi.ts
src/api/tokenList/TokenListApiMock.ts
src/components/OrderBookBtn.tsx
src/components/PoolingWidget/index.tsx
src/hooks/useManageTokens.tsx
src/hooks/useOrders.ts
src/hooks/useTokenBalances.ts
src/hooks/useTokenList.ts
src/pages/OrderBook.tsx
src/services/factories/getTokenFromExchange.ts
src/services/factories/tokenList.ts

Updates logic to avoid the flash of bad data
Still re-mounts data but at least doesn't show wrong numbers. Though I think the flag is probably a bad idea, it looks better. Maybe in the future we move everything to global state and use a flag `isDefault` list or something to let `useOrders` know not to render anything first time.
Thoughts @Velenir ?

1486.5/fix wrong tokens orders logic update

---

src/api/wallet/WalletApi.ts
src/components/TradeWidget/index.tsx
src/hooks/useWalletConnection.ts

Fixes broken line using `buyToken` instead of `receiveToken` and assigns `Network` type to `networkIdOrDefault` inside `useWalletConnection`

fix networkOrDefault type and typo

---

src/components/TradesWidget/TradeRow.tsx
src/components/common/SwapPrice.tsx

Part of https://github.com/gnosis/dex-react/issues/1476
So now that have a smarter way to decide what market is the user viewing, we can use it also for the trades.
Actually, now we could bring the concept of "Side" of the trade.
The side of the trade would be if we are buying or selling.
This PR:
If we invert the market, the user effectively selects a different QUOTE, change the price value and it's units. Also, the TRADE is being seen as a BUY if it was a SELL before, and the other way around:
Future PRs could:
- Move "Side" to its own column. We could get inspiration in https://trade.dydx.exchange/ or our 2.0 designs. @W3stside could you help me with this one?
- Allow to invert the market (the whole row)
- We could consider not displaying 2 prices. Maybe we find a better
- Everything …

[Smart Quote] Show buy sell fills

---

src/components/OrdersWidget/OrdersWidget.styled.ts
src/components/TradeWidget/SwapIcon.tsx
src/components/TradesWidget/TradeRow.tsx
src/components/TradesWidget/index.tsx
src/components/layout/PageWrappers.tsx
src/components/layout/SwapLayout/index.tsx
src/const.ts
src/styles/variables.ts

Part of #1476 
Inside Orders > Trades
Splits `Sell/Bought` column into two separate columns
Changes `Market` with `WETH/DAI` to `Pair` with `Swap DAI for WETH`
SwapPrice comp on `Limit/Fill Price` column

[Smart Quote] TradesRow data rearrangement - swap Limit/Fill price and Sell/Bought column split

---

src/components/OrdersWidget/OrderRow.tsx
src/components/OrdersWidget/index.tsx

Part of #1476 
Rearranges Orders more like Trades:
1. splits `Filled/Total` columns
2. `Swap TokenA for TokenB` format
3. Horizontal scroll

[smart quote] Orders: rearrange data presentation like Trades

---

src/components/TradeWidget/index.tsx
src/components/trade/PriceSuggestions/PriceSuggestionWidget.tsx

`usePriceEstimationWithSlippage` returns price in `quote` token (as it should) but the app wasn't inverting the price when `smart-quote` logic was running thus showing incorrect prices in FE
This fixes that.

[Smart Quote] Fix broken **limitPrice** amount

---

src/components/layout/PageWrappers.tsx
src/components/layout/SwapLayout/index.tsx
src/pages/Wallet.tsx

Closes #1552 
Adds `$autoWidth` prop to set self-resize width on PageWrapper container

1552 Wallet/Balances narrower width

---

src/hooks/usePriceEstimation.ts

Closes #1558 
Merges into #1557 
Fixes the incorrect low volume nujmbers inside the confirmation modal due to switch base/quote tokens

[1558] Fix "Low Volume" inside Confirmation Modal calculation error

---

src/components/OrdersWidget/OrderRow.styled.ts
src/components/OrdersWidget/OrderRow.tsx
src/components/TradesWidget/TradeRow.tsx
src/components/UserWallet/UserWallet.styled.ts
src/components/common/SmartPrice.tsx
src/components/layout/SwapLayout/Card/Card.tsx

Closes #1545 
Shows percentage filled in orders like in trades
Also fixes the Swap TokenSell for TokenBuy bug as it was previously inverted

1545 - Show percentage filled & fix incorrect market order in orders

---

src/styles/fonts.ts

Linter didn't catch it because this though `font-face` was a custom WebComponent, I assume

Fix @font-face

---

src/components/PoolingWidget/PoolingWidget.styled.ts
src/components/layout/SwapLayout/index.tsx

Fixes several CSS fixes found on testing with help from @biocom 
PoolingWidget:
TODO:

[CSS Fixes] PoolingWidget smushed content on resize

---

src/components/TradeWidget/TxMessage.tsx
src/components/trade/PriceSuggestions/PriceSuggestionItem.tsx

Fixes calculation issues found in confirmation modal price impact and fixes smart formatting for small amounts in `Receive at least` input when using really low price and/or 0 sell amount

[Fixes] Warning rounding calculation error + remove smart format from receive amount

---

.travis.yml

Address issue regarding the URL being used for the price estimator:
* Use develop price estimator URL for develop branch and PRs
* Use production only for master, hotfixes, releases and tags
The issue was, that the backslashes in a TRAVIS script expression were causing the URL to be set to `production` always.
Not it should be working as intended

Use develop price estimator URL for develop branch and PRs

---

.travis.yml
package.json

Adds coverage cache
I was unsure if it was safe to cache the coverage, but it looks like it works!
Same report, and the time goes does from 38s to 8s in my machine. Travis will be happy about this.
Try to run:
```bash
yarn test:coverage
yarn test:coverage
yarn test:coverage
```

Cache coverage tests

---

.gitignore
.travis.yml
package.json

Now commiting is again super fast!
The problem is pushing is SLOW. I personally prefer to let travis fail, we already work in branches, and it saves so much time.
The linter already caches most of the issues, all the other should be catched in the "build" of travis.
I wouldn't add `yarn check-types` at all, I did it here in this PR, just for experimenting. We can leave it if our concern is we want to FAIL asap. But, I think it's better to leave that out
EDIT: Following @Velenir tip, I'll try with https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#faster-subsequent-builds-with-the---incremental-flag

Remove push hook

---

src/components/trade/PriceImpact/utils.ts

As title states - on small amounts sometimes the warning was showing up when it shouldnt. 
User selects suggested fillPrice and warning still showed. This prevents that

[1.6] Use limitPrice.eq(fillPrice) to check correctly when there shouldn't be a warning

---

src/api/wallet/composeProvider.ts

Cherry-picked solution from #1614 
Intercepts the error handling, making sure the `data` field is present.
This solves an issue with web3 failing in their error handling, leaving the promises unfulfilled.

Sanitize error data

---

src/api/wallet/composeProvider.ts

This solves Anna's issue with approving tokens using Wallet Connect.
> TLDR: The issue, is that the estimation is failing if we provide a `gasPrice`
yes, really. I'm betting this has to do with yesterday hardfork in some way. https://www.coindesk.com/ethereums-hard-fork-disruption
So this is how we estimate. We just send the same params we would use in the tx, to the `estimateGas` function:
```js
web3.eth.estimateGas({data: "0x095ea7b30000000000000000000000006f400810b62df8e13fded51be75ff5393eaa841fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdec0de02120132", from: "0xd5cbc5e664813c7f1ce0a136aa154ce525e97e21", to: "0x6810e776880c02933d47db1b9fc05908e5386b96", gasPrice: "0xcce416bb4"}, console.log)
```
> Throws error: `react_devtools_backend.js:2450 MetaMask - RPC Error: …

Fix issue approving tokens

---

.eslintrc.js
src/api/wallet/composeProvider.ts

Correcting what was obvious an issue, since in PR hotfix #1618 the `data` was ignored to solve an issue with the hardfork last week.  Only the fields from this method were added https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#methods-mymethod-estimategas, we should have used https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html?highlight=estimateGas#estimategas
Actually, the fix removes the `gasPrice` that breaks the estimation for approving tokens for Anna after last hardfork, although my understanding it should be fine to add them according to JSON-rpc spec
https://eth.wiki/json-rpc/API

Fix issue gas estimation

---

playwright/integration/about.test.ts
playwright/integration/connect_wallet.test.ts

I just wanted to try out what I wrote in one comment of #1625 
> Why do you use a "pattern", is not needed right? (since text selector already searches for partial text matching)
> Also, I think it's more readable the short-form
My understanding is this PR has equivalent selectors

Simplify text selectors

---

.gitignore
package.json
playwright/inject/inject_provider.js
playwright/integration/about.test.ts
playwright/integration/connect_wallet.test.ts
playwright/utils/build_injects.ts
playwright/utils/provider_setup.ts
playwright/utils/test_setup.ts
tsconfig.json
yarn.lock

- Adds Wallet injection into playwright browser (`window.ethereum`)
- Compilation for browser injects step when needed
- Integration test for connecting user wallet
To see it perform and to test/debug please run
```sh
#serve the app
serve -s -l 8080 dist
#in a different terminal
yarn playwright:debug --testNamePattern=wallet
```
Actually please just run that so we can check it works on different machines

Playwright wallet connection test

---

src/components/common/Button/index.stories.tsx
src/components/common/Button/index.tsx
src/storybook/decorators.tsx
src/styles/common/StyledButton.tsx

Changes props `kind` and `size` in Button to `$type` and `$size`, respectively
`$` prepend to adhere to our non-clashing styled component prop naming convention

V2/Button change kind & size prop names

---

src/components/common/Button/index.stories.tsx
src/components/common/Button/index.tsx
src/storybook/decorators.tsx
src/styles/common/StyledButton.tsx
src/styles/styles.ts

:droplet: into #1632
Adds theme capabilities for creating sized versions of buttons and creates a `ThemeProvider` wrapped Button default export
See stories BIG and SMOL to test

[V2] Button sizes

---

src/components/OrderBuySell/index.tsx
src/components/common/Tabs/TabContent.tsx
src/components/common/Tabs/Tabs.tsx

V2 Tabs - Separate PR addressing comments
Addresses comments left in #1629 also waterfalls in

V2 Tabs - Separate PR addressing comments

---

config-default.yaml

Adds WBTC to xDAI default list
TEST: 
* Validate the address is correct
* You can try to make an order for buying or selling WBTC

Add WBTC to xDAI default list

---

src/components/DepositWidget/index.tsx

While fixing `TokenAdder` I noticed you can't search by address in `/wallet` page
Try to input `0xdAC17F958D2ee523a2206206994597C13D831ec7` at https://dex.dev.gnosisdev.com/wallet
You should get `USDT` but get nothing

Fix search by address in /wallet

---

src/hooks/useTokenBalances.ts
src/utils/miscellaneous.ts

- Fixes types
- Simplifies `timeout` function body to reuse already available `utlils/delay`
- Fixes more types
- 
You can see the usefulness of `Promise<never>` [here](https://www.typescriptlang.org/play?target=99&jsx=0&module=1&ts=4.0.5#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQQFtgIBXGABUykyIGcAefAPjgG8AoOOGY4APwAuOEjJEARmm5wowemQA2MYQRl8S5GAFEoUaAFl6Ac1X0YUZMc4BfTp1CRYcbBCTm4AEW0AxAIIAqgAy+AD6+ACSBtoA8gH4cAC8cACsAAwZ9o7Q8K7u8AAmwIqYAJ5JcMwVAG4QCAUsABQMFQCMGQA0svJKKiL4AJQilPpECPTAzGyJLDJIwADucCMQYxONjXL0EIrVwANJbBMwhJoUm-I7e10MXVu9AwNZ4Dlw6GRI2HxuvPxajWAaHR6P0-hRqLQGIwPkV0MhgA0hstRuNJvM9lBZtlnO9Pt8kL8zjApgCgQxQUSIcCqqBUEgCvQ4DDgHD5gU4AJRMAMXB+iwkSs1pNWA4Xs5MPRSp83h8vggfhpSBQSYDISCCGCqGSmKwBSiJlUAD5cjFsLg8PIediEvDJbz+YJhSLROL4O49ZRdRVaXT6KBGYwib0UAMVADkpyVMDDcBsFVVwPsPEwC0wCEKxTKjUVTxkCHQcAuCm …

Improve timeout util

---

src/const.ts
src/hooks/useTokenBalances.ts
src/utils/miscellaneous.ts

We've observed in two occasions now that some Metamask fails to resolve some promise for contract calls. First with the issue of SNX/sUSD proxy deprecation, yesterday with Ledger MM (not it seems it doesn't do that anymore).
When this happens, we neither get a success or an error.
Currently, if for one token, the promise is not resolved, the overall "fetch all balances" promise don't resolve either (uses `Promise.all`)
This PR introduces a timeout for fetching individual tokens for this extreme cases. It uses 10s, maybe it could be less. But theoretically promises should resolve one way or the other!

Add timeout for fetching tokens

---

src/services/factories/tokenList.ts

Why? fixes empty row bug in balances
Problem was:

[Hotfix] Fix empty row bug in balances

---

config-default.yaml
test/config.spec.ts

Use same TCR as mesa for testing
Any project can for dex-react and use their own TCR. For testing the TCR functionality, we could use same as Mesa, since I assume they would provide a rationale on their listing and deprecate old tokens (and check for compatibilities before listing) 
I left as a comment the old TCR we were using, since it can be handy to use back in the future for some tests.

Use same TCR as mesa for testing

---

src/components/common/Button/index.tsx
src/reducers-actions/tokenRow.ts
src/storybook/decorators.tsx
src/theme/index.ts
src/theme/index.tsx
src/theme/types.ts
src/theme/utils.ts

Part of #1660 and :water_buffalo: 's into #1667 
Enhances the default `styled-components` `ThemeProvider` wrapper and passes in our `theme` - also adds the benefit of implicitly passing it to any children
1. uses the `useThemeManager` hook and redux data from previous PR to detect selected theme and adjust accordingly.
2. Wraps ThemeToggler inside `storybook > decorators` with `withGlobalContext` inorder to access global state and use the theme provider
3. adds a `utils` file inside `theme` for some common utils. `getColourPalette` returns the `themeMode` specific `colourPalette`

[V2 #1660 Style Rework] - Enhance ThemeProvider

---

package.json
yarn.lock

> Originally created by @W3stside 
Versions for `web3` and `web3modal` updated in one of the PRs, causing breakage in the `playwright` tests.
`Web3Modal` likely updated and subsequently installed a higher `web3` version which took precedence.
1. `web3@1.3.1` >> `web3@1.2.9`
2. `web3modal@1.9.3` >> `web3modal@1.9.0`
Maybe we need to fix this later and not rely on pinning...
Playwright tests are passing:

Fix integration tests: Pin dependencies
